### ISSUE TITLE
[libretro-db] Failed to build lua_common.c

### ISSUE THREAD

**Issue by RobLoach** [libretro/RetroArch#2645]
Can't build libretro-db lua_converter.o:

```
git clone git@github.com:libretro/RetroArch.git
cd RetroArch
make
cd libretro-db
make
```

Result is...

```
cc -I. -I../libretro-common/include lua_common.c -c -g -O2 -o lua_common.o
In file included from lua_common.c:1:0:
lua_common.h:4:17: fatal error: lua.h: No such file or directory
compilation terminated.
Makefile:76: recipe for target 'lua_common.o' failed
make: *** [lua_common.o] Error 1
```

cc @leiradel

**Comment by sergiobenrocha2** [comment]
If you are on Debian/Ubuntu, you have to apply this patch:

```
Index: RetroArch-git/libretro-db/Makefile
===================================================================
--- RetroArch-git.orig/libretro-db/Makefile	2015-12-28 11:52:06.757140583 -0200
+++ RetroArch-git/libretro-db/Makefile	2015-12-28 11:54:14.491015827 -0200
@@ -65,7 +65,7 @@
 
 RMSGPACK_OBJS := $(RMSGPACK_C:.c=.o)
 
-LUA_FLAGS     = `pkg-config lua --libs`
+LUA_FLAGS     = `pkg-config lua5.2 --libs`
 TESTLIB_FLAGS = ${CFLAGS} ${LUA_FLAGS} -shared -fpic
 
 .PHONY: all clean check
Index: RetroArch-git/libretro-db/lua_common.h
===================================================================
--- RetroArch-git.orig/libretro-db/lua_common.h	2015-12-28 11:52:13.657241880 -0200
+++ RetroArch-git/libretro-db/lua_common.h	2015-12-28 11:54:26.163187185 -0200
@@ -1,9 +1,9 @@
 #ifndef __RARCHDB_LUA_COMMON_H__
 #define __RARCHDB_LUA_COMMON_H__
 
-#include <lua.h>
-#include <lualib.h>
-#include <lauxlib.h>
+#include <lua5.2/lua.h>
+#include <lua5.2/lualib.h>
+#include <lua5.2/lauxlib.h>
 
 #include "rmsgpack_dom.h"
 
Index: RetroArch-git/libretro-db/lua_converter.c
===================================================================
--- RetroArch-git.orig/libretro-db/lua_converter.c	2015-12-28 11:52:10.329192818 -0200
+++ RetroArch-git/libretro-db/lua_converter.c	2015-12-28 11:54:20.531104501 -0200
@@ -5,9 +5,9 @@
 #include <string.h>
 #include <stdlib.h>
 
-#include <lua.h>
-#include <lualib.h>
-#include <lauxlib.h>
+#include <lua5.2/lua.h>
+#include <lua5.2/lualib.h>
+#include <lua5.2/lauxlib.h>
 
 #include "libretrodb.h"
 #include "lua_common.h"

```

**Comment by RobLoach** [comment]
With that, I get:

```
➜  libretro-db git:(master) ✗ make
cc -I. -I../libretro-common/include -Ilibretro-lutro/deps/lua/src rmsgpack.o rmsgpack_dom.o lua_common.o libretrodb.o bintree.o query.o lua_converter.o ../libretro-common/compat/compat_fnmatch.o ../libretro-common/file/retro_file.o ../libretro-common/compat/compat_strl.o `pkg-config --libs` -o lua_converter
Must specify package names on the command line
lua_common.o: In function `libretrodb_lua_to_rmsgpack_value':
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:22: undefined reference to `lua_pushnil'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:95: undefined reference to `lua_settop'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:23: undefined reference to `lua_next'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:27: undefined reference to `lua_isstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:29: undefined reference to `lua_type'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:36: undefined reference to `lua_tolstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:42: undefined reference to `lua_type'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:60: undefined reference to `lua_getfield'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:61: undefined reference to `lua_isstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:63: undefined reference to `lua_settop'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:64: undefined reference to `lua_getfield'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:65: undefined reference to `lua_isnumber'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:72: undefined reference to `lua_tonumber'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:51: undefined reference to `lua_toboolean'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:67: undefined reference to `lua_settop'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:45: undefined reference to `lua_tonumber'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:54: undefined reference to `lua_tolstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:80: undefined reference to `lua_tolstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_common.c:86: undefined reference to `lua_settop'
lua_converter.o: In function `value_provider':
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:47: undefined reference to `lua_getglobal'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:49: undefined reference to `lua_pcallk'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:57: undefined reference to `lua_type'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:63: undefined reference to `lua_settop'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:59: undefined reference to `lua_type'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:51: undefined reference to `lua_tolstring'
lua_converter.o: In function `main':
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:83: undefined reference to `luaL_newstate'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:85: undefined reference to `luaL_openlibs'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:86: undefined reference to `luaL_loadstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:88: undefined reference to `luaL_loadfilex'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:88: undefined reference to `lua_pcallk'
lua_converter.o: In function `call_init':
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:27: undefined reference to `lua_getglobal'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:29: undefined reference to `lua_pushstring'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:31: undefined reference to `lua_pcallk'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:33: undefined reference to `lua_tolstring'
lua_converter.o: In function `main':
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:108: undefined reference to `lua_close'
/tmp/libretro-database/RetroArch/libretro-db/lua_converter.c:86: undefined reference to `lua_pcallk'
collect2: error: ld returned 1 exit status
Makefile:82: recipe for target 'lua_converter' failed
make: *** [lua_converter] Error 1
```

**Comment by sergiobenrocha2** [comment]
It worked with lua 5.2 on ubuntu 14.04...

Are you sure you applied the patch fully? These undefined reference 
should be from the wrong linkage at the end, you must use:

|LUA_FLAGS = `pkg-config lua5.2 --libs`|

**Comment by sergiobenrocha2** [comment]
ugh...

LUA_FLAGS     = `pkg-config lua5.2 --libs`

**Comment by twinaphex** [comment]
I never wanted Lua dependencies and exactly for this reason.

Unfortunately, I could not convince the external developer who wrote this to do it in plain C, so as usual, the maintenance problems become my problems then as they are far away nowhere to be seen once the initial implementation is done.

**Comment by leiradel** [comment]
Isn't the C version I coded a while back working?


Sent from my Samsung device

-------- Original message --------

**Comment by RobLoach** [comment]
`plain_converter`?

**Comment by twinaphex** [comment]
@leiradel It doesn't work with multiple DAT iteration.

**Comment by leiradel** [comment]
It's been quite some time, but I was pretty sure it could process multiple DAT files. I'll take a look when I'm back from vacation.


Sent from my Samsung device

-------- Original message --------

**Comment by twinaphex** [comment]
Did you check if the rdbs it generated were identical to the ones generated by the Lua equivalents though? Last time I checked they weren't.

**Comment by leiradel** [comment]
Hm, maybe the a good compromise would be to add the Lua source code to libretro-db? It could be compiled along with libretro-db, so no missing headers and libs. Lua compiles unchanged pretty much everywhere.

I do that with gw-libretro and it has never been an issue. As a bonus, I don't have to worry about new Lua releases.

**Comment by twinaphex** [comment]
Which repo are you talking about here when you talk about libretro-db? RetroArch or some other repo?

Lua source in RetroArch repo is not going to happen, and as for it appearing in any other repo, I really don't want to be dependent on Lua. I don't want to jump through any of these dependencies' hoops whenever they bump the API and you have to update a whole bunch of code again just to have your program stay working. That is why it is either C/C++ or bust.

**Comment by leiradel** [comment]
Yes, RetroArch, like `RetroArch/libretro-db/lua`.

As for API bumps, you're missing the point. What I said would effectively freeze the Lua version used in libretro-db programs, and the Lua source code would be compiled along them, so the Lua version the user has in her system wouldn't matter,

Since Lua authors has a C89 compatibility policy with its source code, it can be compiled pretty much anywhere. I dare to say Lua compiles in more platforms that RetroArch, so adding its source code to libretro-db should be a non-issue.

**Comment by twinaphex** [comment]
No way. I am never going to add Lua sources to RetroArch. This is a terrible idea.

The only solution here is moving off Lua dependencies.

**Comment by leiradel** [comment]
Ok, it's your call. I just fail to see why doing that is so terrible. To me it's almost the same as `#include <stdlib.h>` and then calling `qsort`.

**Comment by twinaphex** [comment]
Because I don't want to pull in a big truckload of source files that we didn't even write into a codebase that is already becoming big as-is, and also because people are almost guaranteed never to have all these dependencies - which is the entire reason the OP of this thread started this thread to begin with. If it had just required a C/C++ compiler and a suitable toolchain, he wouldn't even have to make this thread in the first place. Ergo we failed and fucked up by having this thing be Lua-dependent in the first place which requires a dependency which otherwise wouldn't be there.

I believe in keeping things as convenient for external developers as much as keeping it convenient for users. Asking a developer to pull in a bunch of external dependencies before he can compile and build RetroArch and the assets it requires is not convenient.

**Comment by leiradel** [comment]
The developer wouldn't have to pull any external dependencies since `git clone` would bring the Lua source code present in the repo, just like what the gw-libretro repo does. Then `make` should be able to compile everything just fine.

Lua source code ammounts to 600Kb, which is hardly a truckload, though I understand that if you add lots of external dependencies into RetroArch it adds up.

Anyway, I'll take a look at the plain converter when I'm back from vacations and see why it's not generating the same output as the Lua converter.

**Comment by twinaphex** [comment]
Can you share the sources to your C-based version of this DAT converter again? @aliaspider might want to take a look at it.

**Comment by leiradel** [comment]
It's in the libretro-db folder, as plain_converter.c, lexer.h/c and parser.h/c

**Comment by fr500** [comment]
if this is still happening, please reopen, I think a C alternative has been implemented already
