### ISSUE TITLE
Segfault with SDL and SDL2 video drivers

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#8374]
## Description

When starting RetroArch with the SDL or SDL2 video drivers it immediately crashes.

### Expected behavior

The SDL and SDL2 video drivers should work.

### Actual behavior

Backtrace with SDL2.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00000000006736e3 in x11_display_server_get_screen_orientation ()
    at gfx/display_servers/dispserv_x11.c:470
470	   XRRScreenResources *screen = XRRGetScreenResources(g_x11_dpy, DefaultRootWindow(g_x11_dpy));
(gdb) bt
#0  0x00000000006736e3 in x11_display_server_get_screen_orientation ()
    at gfx/display_servers/dispserv_x11.c:470
#1  0x000000000047885a in video_display_server_get_screen_orientation ()
    at gfx/video_display_server.c:145
#2  0x0000000000478536 in video_display_server_init ()
    at gfx/video_display_server.c:67
#3  0x0000000000479df3 in video_driver_init_internal (
    video_is_threaded=0x7fffffffdc07) at gfx/video_driver.c:1115
#4  0x000000000047aff4 in video_driver_init (video_is_threaded=0x7fffffffdc07)
    at gfx/video_driver.c:1761
#5  0x00000000004803a6 in drivers_init (flags=1023) at driver.c:365
#6  0x0000000000416470 in retroarch_main_init (argc=1, argv=0x7fffffffe208)
    at retroarch.c:1445
#7  0x00000000004314e7 in content_load (info=0x7fffffffe0d0)
    at tasks/task_content.c:291
#8  0x000000000043277e in task_load_content (content_info=0x7fffffffe0d0, 
    content_ctx=0x7fffffffdfe0, launched_from_menu=true, launched_from_cli=true, 
    error_string=0x7fffffffdfd8) at tasks/task_content.c:982
#9  0x0000000000433c75 in task_load_content_callback (
    content_info=0x7fffffffe0d0, loading_from_menu=true, loading_from_cli=true)
    at tasks/task_content.c:1672
#10 0x0000000000433e84 in task_push_load_content_from_cli (core_path=0x0, 
    fullpath=0x0, content_info=0x7fffffffe0d0, type=CORE_TYPE_PLAIN, cb=0x0, 
    user_data=0x0) at tasks/task_content.c:1753
#11 0x000000000041280d in rarch_main (argc=1, argv=0x7fffffffe208, data=0x0)
    at frontend/frontend.c:140
#12 0x0000000000412890 in main (argc=1, argv=0x7fffffffe208)
    at frontend/frontend.c:184
```
Full GDB log - https://paste.ee/p/71Bn7
```
$ ./retroarch
AddressSanitizer:DEADLYSIGNAL
=================================================================
==26462==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000e8 (pc 0x000000907e28 bp 0x7ffee83bf140 sp 0x7ffee83bf110 T0)
==26462==The signal is caused by a READ memory access.
==26462==Hint: address points to the zero page.
    #0 0x907e27 in x11_display_server_get_screen_orientation gfx/display_servers/dispserv_x11.c:470
    #1 0x507b35 in video_display_server_get_screen_orientation gfx/video_display_server.c:145
    #2 0x507596 in video_display_server_init gfx/video_display_server.c:67
    #3 0x50acc0 in video_driver_init_internal gfx/video_driver.c:1115
    #4 0x50cfe6 in video_driver_init gfx/video_driver.c:1761
    #5 0x519aab in drivers_init /home/orbea/gittings/forks/RetroArch/driver.c:365
    #6 0x42152b in retroarch_main_init /home/orbea/gittings/forks/RetroArch/retroarch.c:1445
    #7 0x44b1c3 in content_load tasks/task_content.c:291
    #8 0x44e185 in task_load_content tasks/task_content.c:982
    #9 0x452573 in task_load_content_callback tasks/task_content.c:1672
    #10 0x45298f in task_push_load_content_from_cli tasks/task_content.c:1753
    #11 0x41a6df in rarch_main frontend/frontend.c:140
    #12 0x41a8a3 in main frontend/frontend.c:184
    #13 0x7f55b560bb5a in __libc_start_main (/lib64/libc.so.6+0x23b5a)
    #14 0x40fe59 in _start (/media/gittings/forks/RetroArch/retroarch+0x40fe59)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV gfx/display_servers/dispserv_x11.c:470 in x11_display_server_get_screen_orientation
==26462==ABORTING
```

### Steps to reproduce the bug

1. Build RetroArch with SDL or SDL2 support.
2. Select the `SDL` or `SDL2` video driver.
3. Start RetroArch

### Bisect Results

```
97b751242056f05bde1b499d528ab8b981e85c2e is the first bad commit
commit 97b751242056f05bde1b499d528ab8b981e85c2e
Author: Brad Parker <cbparker@gmail.com>
Date:   Sat Feb 23 14:15:36 2019 -0500

    restore initial screen orientation on exit for x11/win32

:040000 040000 d429baf82a88a9185356c80ffd2461dbe7679a1b b73edf8f441ccfd8f60b9f095084f3cc0127756b M	gfx
:100644 100644 9b846922d9ebdce923753df698a9ad59530feb74 0a39cdf98fab5573aea4148c2ac2e8b4e0daa89a M	retroarch.c
:040000 040000 ff161ef18cb61e7800adf0599cec32e75f7f1d9d 7e78718580ef2937dd0e13c0654c74d2bae64e2c M	ui
```
97b751242056f05bde1b499d528ab8b981e85c2e

### Version/Commit
You can find this information under Information/System Information

- RetroArch: https://github.com/libretro/RetroArch/commit/0aa9df6acd91212880150554651573d9571f1697

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-8.3.0`
- SDL: `2.0.9`/`1.2.15`

**Comment by orbea** [comment]
@bparker06 Would you mind looking at this?

**Comment by orbea** [comment]
It doesn't crash with `--disable-xrandr`, but then it crashes when starting a core from the menu (History list). It works from the command-line.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000000000695ada in sdl2_poke_set_aspect_ratio (data=0x0, aspect_ratio_idx=22)
    at gfx/drivers/sdl2_gfx.c:665
665	   vid->video.force_aspect = true;
(gdb) bt
#0  0x0000000000695ada in sdl2_poke_set_aspect_ratio (data=0x0, 
    aspect_ratio_idx=22) at gfx/drivers/sdl2_gfx.c:665
#1  0x000000000047b057 in video_driver_set_aspect_ratio ()
    at gfx/video_driver.c:1809
#2  0x0000000000420429 in command_event (cmd=CMD_EVENT_VIDEO_SET_ASPECT_RATIO, 
    data=0x0) at command.c:2359
#3  0x000000000049afb8 in rarch_environment_cb (cmd=37, data=0x7fffffffb4e0)
    at dynamic.c:1896
#4  0x00007ffff049f026 in check_variables () at ../libretro/libretro.cpp:904
#5  0x00007ffff04a03d7 in retro_load_game (info=0x1436560)
    at ../libretro/libretro.cpp:1158
#6  0x0000000000413b26 in core_load_game (load_info=0x7fffffffc190)
    at core_impl.c:307
#7  0x0000000000431e5b in content_file_load (info=0x1436560, content=0x1436310, 
    content_ctx=0x7fffffffc270, error_string=0x7fffffffc268, special=0x0, 
    additional_path_allocs=0x1436590) at tasks/task_content.c:721
#8  0x0000000000432482 in content_file_init (content_ctx=0x7fffffffc270, 
    content=0x1436310, error_string=0x7fffffffc268) at tasks/task_content.c:913
#9  0x0000000000434652 in content_init () at tasks/task_content.c:2102
#10 0x000000000041e686 in event_init_content () at command.c:1293
#11 0x000000000041e7fe in command_event_init_core (
    data=0xa5ef88 <current_core_type>) at command.c:1361
#12 0x00000000004203e8 in command_event (cmd=CMD_EVENT_CORE_INIT, 
    data=0xa5ef88 <current_core_type>) at command.c:2347
#13 0x0000000000416349 in retroarch_main_init (argc=10, argv=0x7fffffffc860)
    at retroarch.c:1419
#14 0x0000000000431427 in content_load (info=0x7fffffffca50)
    at tasks/task_content.c:291
#15 0x00000000004326be in task_load_content (content_info=0x7fffffffca50, 
    content_ctx=0x7fffffffcac0, launched_from_menu=true, 
    launched_from_cli=false, error_string=0x7fffffffcab8)
    at tasks/task_content.c:982
#16 0x00000000004329aa in command_event_cmd_exec (
    data=0x13b0010 "Castlevania.nes", content_ctx=0x7fffffffcac0, 
    launched_from_cli=false, error_string=0x7fffffffcab8)
    at tasks/task_content.c:1099
#17 0x00000000004330f5 in task_push_load_content_from_playlist_from_menu (
    core_path=0x7fffffffcc10 "/media/gittings/forks/RetroArch/nestopia_libretro.so", fullpath=0x13b0010 "Castlevania.nes", label=0x0, content_info=0x7fffffffcb70, 
    cb=0x0, user_data=0x0) at tasks/task_content.c:1318
#18 0x000000000060e7a2 in default_action_ok_load_content_from_playlist_from_menu
    (
    _path=0x7fffffffcc10 "/media/gittings/forks/RetroArch/nestopia_libretro.so", 
    path=0x13b0010 "Castlevania.nes", entry_label=0x0)
    at menu/cbs/menu_cbs_ok.c:1588
#19 0x000000000060f391 in action_ok_playlist_entry_collection (
    path=0x13b0010 "Castlevania.nes", label=0x13b9ab0 "collection", type=7, 
    idx=0, entry_idx=0) at menu/cbs/menu_cbs_ok.c:1802
#20 0x000000000060acec in menu_entry_action (entry=0x7fffffffdcd0, i=0, 
    action=MENU_ACTION_OK) at menu/widgets/menu_entry.c:471
#21 0x0000000000658a95 in generic_menu_iterate (menu=0x12d37e0, 
    userdata=0x12d9c10, action=MENU_ACTION_OK) at menu/drivers/menu_generic.c:232
#22 0x00000000005e6851 in menu_driver_iterate (iterate=0x7fffffffde90)
    at menu/menu_driver.c:2039
#23 0x0000000000418d1f in runloop_check_state (settings=0x7ffff116b010, 
    input_nonblock_state=false, runloop_is_paused=false, fastforward_ratio=5, 
    sleep_ms=0x7fffffffe0f0) at retroarch.c:3028
#24 0x000000000041a10e in runloop_iterate (sleep_ms=0x7fffffffe0f0)
    at retroarch.c:3743
#25 0x0000000000412773 in rarch_main (argc=1, argv=0x7fffffffe208, data=0x0)
    at frontend/frontend.c:156
#26 0x00000000004127d0 in main (argc=1, argv=0x7fffffffe208)
    at frontend/frontend.c:184
```
Full GDB log - https://paste.ee/p/zdhED
```
$ ./retroarch
AddressSanitizer:DEADLYSIGNAL
=================================================================
==14961==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000000aa (pc 0x00000096d6ca bp 0x7ffe4c41c1e0 sp 0x7ffe4c41c1c0 T0)
==14961==The signal is caused by a WRITE memory access.
==14961==Hint: address points to the zero page.
    #0 0x96d6c9 in sdl2_poke_set_aspect_ratio gfx/drivers/sdl2_gfx.c:665
    #1 0x50d198 in video_driver_set_aspect_ratio gfx/video_driver.c:1809
    #2 0x434edc in command_event /home/orbea/gittings/forks/RetroArch/command.c:2359
    #3 0x55762e in rarch_environment_cb /home/orbea/gittings/forks/RetroArch/dynamic.c:1896
    #4 0x7f3eaa980025 in check_variables ../libretro/libretro.cpp:904
    #5 0x7f3eaa9813d6 in retro_load_game ../libretro/libretro.cpp:1158
    #6 0x41d201 in core_load_game /home/orbea/gittings/forks/RetroArch/core_impl.c:307
    #7 0x44c931 in content_file_load tasks/task_content.c:721
    #8 0x44d9cd in content_file_init tasks/task_content.c:913
    #9 0x453ccd in content_init tasks/task_content.c:2102
    #10 0x4313e1 in event_init_content /home/orbea/gittings/forks/RetroArch/command.c:1293
    #11 0x4317a9 in command_event_init_core /home/orbea/gittings/forks/RetroArch/command.c:1361
    #12 0x434e36 in command_event /home/orbea/gittings/forks/RetroArch/command.c:2347
    #13 0x4213fe in retroarch_main_init /home/orbea/gittings/forks/RetroArch/retroarch.c:1419
    #14 0x44b103 in content_load tasks/task_content.c:291
    #15 0x44e0c5 in task_load_content tasks/task_content.c:982
    #16 0x44e7e6 in command_event_cmd_exec tasks/task_content.c:1099
    #17 0x4500d1 in task_push_load_content_from_playlist_from_menu tasks/task_content.c:1318
    #18 0x828361 in default_action_ok_load_content_from_playlist_from_menu menu/cbs/menu_cbs_ok.c:1588
    #19 0x8297d8 in action_ok_playlist_entry_collection menu/cbs/menu_cbs_ok.c:1802
    #20 0x81f7df in menu_entry_action menu/widgets/menu_entry.c:471
    #21 0x8c0274 in generic_menu_iterate menu/drivers/menu_generic.c:232
    #22 0x7d63be in menu_driver_iterate menu/menu_driver.c:2039
    #23 0x42606a in runloop_check_state /home/orbea/gittings/forks/RetroArch/retroarch.c:3028
    #24 0x428559 in runloop_iterate /home/orbea/gittings/forks/RetroArch/retroarch.c:3743
    #25 0x41a6ad in rarch_main frontend/frontend.c:156
    #26 0x41a7e3 in main frontend/frontend.c:184
    #27 0x7f3eb26f3b5a in __libc_start_main (/lib64/libc.so.6+0x23b5a)
    #28 0x40fd99 in _start (/media/gittings/forks/RetroArch/retroarch+0x40fd99)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV gfx/drivers/sdl2_gfx.c:665 in sdl2_poke_set_aspect_ratio
==14961==ABORTING
```

**Comment by bparker06** [comment]
should be fixed in 211515ece1

**Comment by orbea** [comment]
@bparker06 That fixed the crash when starting with SDL1 and SDL2 while breaking the build with `--disable-xrandr` which was fixed in https://github.com/libretro/RetroArch/pull/8349.
```
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_open_display’:
gfx/display_servers/dispserv_x11.c:64:7: error: ‘x11_display_server_using_global_dpy’ undeclared (first use in this function); did you mean ‘x11_display_server_open_display’?
       x11_display_server_using_global_dpy = true;
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       x11_display_server_open_display
gfx/display_servers/dispserv_x11.c:64:7: note: each undeclared identifier is reported only once for each function it appears in
gfx/display_servers/dispserv_x11.c: In function ‘x11_display_server_close_display’:
gfx/display_servers/dispserv_x11.c:77:16: error: ‘x11_display_server_using_global_dpy’ undeclared (first use in this function); did you mean ‘x11_display_server_open_display’?
    if (!dpy || x11_display_server_using_global_dpy || dpy == g_x11_dpy)
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                x11_display_server_open_display
At top level:
gfx/display_servers/dispserv_x11.c:75:13: warning: ‘x11_display_server_close_display’ defined but not used [-Wunused-function]
 static void x11_display_server_close_display(Display *dpy)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gfx/display_servers/dispserv_x11.c:59:17: warning: ‘x11_display_server_open_display’ defined but not used [-Wunused-function]
 static Display* x11_display_server_open_display(void)
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CC gfx/drivers_context/drm_ctx.c
make: *** [Makefile:200: obj-unix/release/gfx/display_servers/dispserv_x11.o] Error 1
make: *** Waiting f
```

The crash when starting content is still present, but it only seems to affect SDL2.

**Comment by bparker06** [comment]
Pushed 4ec71da9a94c5ded73c4fff7e7ae1dfb4f966f48 for `--disable-xrandr` fix and also made a temporary fix for the SDL2 crash on load content in 433cbb021f75bcc843bd3e7191cbf16c225f9379... it's completely the wrong solution and needs a proper fix, but for now it at least shouldn't crash.

**Comment by orbea** [comment]
Thanks.

The crash is resolved, but as you said its not correct and now takes the user back to the menu with `Run`, toggling the quick menu a few times starts content.

**Comment by orbea** [comment]
I'm not sure what's up with the remaining issue, I went back to `v1.3.6` and could reproduce it. Maybe something in SDL2 changed?

**Comment by orbea** [comment]
@bparker06 It seems `video_driver_data` is always a `nil` value with other video drivers too, see `gl.c`.

https://github.com/libretro/RetroArch/blob/433cbb021f75bcc843bd3e7191cbf16c225f9379/gfx/drivers/gl.c#L3993

https://github.com/libretro/RetroArch/blob/433cbb021f75bcc843bd3e7191cbf16c225f9379/gfx/video_driver.c#L1065

So the graphics not updating when launching content might be a unrelated problem? I'm puzzled why no one noticed this before?

**Comment by orbea** [comment]
@bparker06 With this SDL2 seems to work correctly, does this look right to you?
```
diff --git a/gfx/drivers/sdl2_gfx.c b/gfx/drivers/sdl2_gfx.c
index eb13938958..837c8a9435 100644
--- a/gfx/drivers/sdl2_gfx.c
+++ b/gfx/drivers/sdl2_gfx.c
@@ -662,12 +662,8 @@ static void sdl2_poke_set_aspect_ratio(void *data, unsigned aspect_ratio_idx)
 
    video_driver_set_aspect_ratio_value(aspectratio_lut[aspect_ratio_idx].value);
 
-   /* FIXME: Why is vid NULL here when starting content? */
-   if (vid)
-   {
-      vid->video.force_aspect = true;
-      vid->should_resize = true;
-   }
+   vid->video.force_aspect = true;
+   vid->should_resize = true;
 }
 
 static void sdl2_poke_apply_state_changes(void *data)
@@ -775,6 +771,7 @@ video_driver_t video_sdl2 = {
    sdl2_gfx_suppress_screensaver,
    sdl2_gfx_has_windowed,
    sdl2_gfx_set_shader,
+   sdl2_gfx_poke_interface
    sdl2_gfx_free,
    "sdl2",
 
@@ -784,7 +781,6 @@ video_driver_t video_sdl2 = {
    sdl2_gfx_read_viewport,
    NULL, /* read_frame_raw */
 #ifdef HAVE_OVERLAY
-    NULL,
+   NULL
 #endif
-    sdl2_gfx_poke_interface
 };
```

**Comment by bparker06** [comment]
No, all that did was move the poke interface to the wrong place so that it doesn't exist in RA's eyes, preventing that function from being called. You should have gotten a warning about it too, because you're essentially using `sdl2_gfx_poke_interface` as `sdl2_gfx_free`, which has a different function signature.

**Comment by orbea** [comment]
Okay, thanks for pointing that out. I was trying to look at it and it seems like `video_driver_data` is freed in `_free` and then expected to exist in `_poke_interface`. At the very least it did avoid the problem. Do you have a better idea?

**Comment by bparker06** [comment]
In theory the poke interface is only supposed to be used while `video_driver_data` *does* exist, and I confirmed both with sdl2 and other drivers that video_driver_data is not normally null... otherwise everything would be quite broken. *Except*, while loading content, it does appear to be null briefly, I guess that's why other drivers have the same check... that function is actually called several times during content load, and the last time it's called, it seems video_driver_data does exist and so it eventually does what it's supposed to, I guess... but yes internally there are several things in RA that have init/deinit order issues.

For now I guess the fix I put in is the best we can do, there is some other fundamental issue with it being called while the driver data is freed but that's not an SDL issue. The run screen appearing must also be a different problem.

I also cannot use my keyboard with the sdl2 driver at all, it simply does not respond to any keys, even escape, but my gamepad works fine.

**Comment by orbea** [comment]
I spent some time trying to debug it with `printf` last night and found that `video_driver_data` is set in `_init`, set to `NULL` in `_free` (And `_destroy`) where it doesn't exist in `_poke_interface`, set again in `_init` and then it exists in `_poke_interface`.

And yes, this is not really a SDL issue, the remaining SDL issue is that when loading content it doesn't clear the quick menu and will attempt to render content on top of the quick menu. My incorrect fix somehow resolved this.

Additionally overlays don't work with SDL2, but that is a different issue...

**Comment by bparker06** [comment]
@orbea Apparently the root of the issue seems to be that it's against the libretro API spec to call SET_GEOMETRY from outside of `retro_run`, which is what snes9x was doing in my case... and perhaps other cores too.

**Comment by orbea** [comment]
I experienced this with nestopia and snes9x, do you have an example fix for a core? I'll look to see where else its happening...

**Comment by fr500** [comment]
I'll try to fix snes9x

**Comment by fr500** [comment]
hmmm seems someone did already

**Comment by orbea** [comment]
Yep, nestopia probably still needs to be fixed and I still need to make new issues for the remaining problems and close this one...

I wouldn't be surprised if at least a few more cores need fixes too, but finding them all might be hard...

**Comment by bparker06** [comment]
Should this be closed now?
