### ISSUE TITLE
[Linux] fails to link after Discord integration

### ISSUE THREAD

**Issue by felinben** [libretro/RetroArch#7080]
## Description

LD retroarch fails

### Expected behavior

LD retroarch issues its binaries

### Actual behavior

[...]
CXX deps/discord-rpc/src/discord_rpc.cpp
In file included from deps/discord-rpc/src/rpc_connection.h:4:0,
                 from deps/discord-rpc/src/discord_rpc.cpp:6:
deps/discord-rpc/src/serialization.h:6:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 ^
deps/discord-rpc/src/serialization.h:8:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 ^
deps/discord-rpc/src/serialization.h:9:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 ^
deps/discord-rpc/src/serialization.h:10:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 ^
deps/discord-rpc/src/serialization.h:11:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 ^
deps/discord-rpc/src/serialization.h:12:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 ^
In file included from deps/discord-rpc/src/rpc_connection.h:4:0,
                 from deps/discord-rpc/src/discord_rpc.cpp:6:
deps/discord-rpc/src/serialization.h:20:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 ^
CXX deps/discord-rpc/src/rpc_connection.cpp
In file included from deps/discord-rpc/src/rpc_connection.h:4:0,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/src/serialization.h:6:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 ^
deps/discord-rpc/src/serialization.h:8:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 ^
deps/discord-rpc/src/serialization.h:9:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 ^
deps/discord-rpc/src/serialization.h:10:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 ^
deps/discord-rpc/src/serialization.h:11:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 ^
deps/discord-rpc/src/serialization.h:12:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 ^
In file included from deps/discord-rpc/src/rpc_connection.h:4:0,
                 from deps/discord-rpc/src/rpc_connection.cpp:1:
deps/discord-rpc/src/serialization.h:20:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 ^
CXX deps/discord-rpc/src/serialization.cpp
In file included from deps/discord-rpc/src/serialization.cpp:1:0:
deps/discord-rpc/src/serialization.h:6:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(push)
 ^
deps/discord-rpc/src/serialization.h:8:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4061) // enum is not explicitly handled by a case label
 ^
deps/discord-rpc/src/serialization.h:9:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4365) // signed/unsigned mismatch
 ^
deps/discord-rpc/src/serialization.h:10:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4464) // relative include path contains
 ^
deps/discord-rpc/src/serialization.h:11:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 4668) // is not defined as a preprocessor macro
 ^
deps/discord-rpc/src/serialization.h:12:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(disable : 6313) // Incorrect operator
 ^
In file included from deps/discord-rpc/src/serialization.cpp:1:0:
deps/discord-rpc/src/serialization.h:20:0: warning: ignoring #pragma warning  [-Wunknown-pragmas]
 #pragma warning(pop)
 ^
CC discord/discord.c
CXX deps/discord-rpc/src/discord_register_linux.cpp
CXX deps/discord-rpc/src/connection_unix.cpp
CC input/input_remote.c
CC cores/libretro-net-retropad/net_retropad_core.c
CC deps/miniupnpc/igd_desc_parse.c
CC deps/miniupnpc/upnpreplyparse.c
CC deps/miniupnpc/upnpcommands.c
CC deps/miniupnpc/upnperrors.c
CC deps/miniupnpc/connecthostport.c
CC deps/miniupnpc/portlistingparse.c
CC deps/miniupnpc/receivedata.c
CC deps/miniupnpc/upnpdev.c
CC deps/miniupnpc/minissdpc.c
CC deps/miniupnpc/miniwget.c
CC deps/miniupnpc/miniupnpc.c
CC deps/miniupnpc/minixml.c
CC deps/miniupnpc/minisoap.c
CC tasks/task_decompress.c
CC led/drivers/led_rpi.c
LD retroarch
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_Shutdown':
discord_rpc.cpp:(.text+0x48): undefined reference to `std::condition_variable::notify_all()'
discord_rpc.cpp:(.text+0x6b): undefined reference to `std::condition_variable::notify_all()'
discord_rpc.cpp:(.text+0x7a): undefined reference to `std::condition_variable::~condition_variable()'
discord_rpc.cpp:(.text+0x82): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0xad): undefined reference to `std::thread::join()'
discord_rpc.cpp:(.text+0xc5): undefined reference to `std::thread::join()'
discord_rpc.cpp:(.text+0xd1): undefined reference to `std::terminate()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_UpdatePresence':
discord_rpc.cpp:(.text+0x16a): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_ClearPresence':
discord_rpc.cpp:(.text+0x21a): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_RunCallbacks':
discord_rpc.cpp:(.text+0x651): undefined reference to `std::__throw_system_error(int)'
discord_rpc.cpp:(.text+0x68c): undefined reference to `std::__throw_system_error(int)'
discord_rpc.cpp:(.text+0x716): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:discord_rpc.cpp:(.text+0x71d): more undefined references to `std::__throw_system_error(int)' follow
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_UpdateHandlers':
discord_rpc.cpp:(.text+0x9c0): undefined reference to `std::condition_variable::notify_all()'
discord_rpc.cpp:(.text+0xa50): undefined reference to `std::condition_variable::notify_all()'
discord_rpc.cpp:(.text+0xae0): undefined reference to `std::condition_variable::notify_all()'
discord_rpc.cpp:(.text+0xc0b): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_Initialize':
discord_rpc.cpp:(.text+0x175a): undefined reference to `std::nothrow'
discord_rpc.cpp:(.text+0x1763): undefined reference to `operator new(unsigned long, std::nothrow_t const&)'
discord_rpc.cpp:(.text+0x1789): undefined reference to `std::condition_variable::condition_variable()'
discord_rpc.cpp:(.text+0x18fc): undefined reference to `operator new(unsigned long)'
discord_rpc.cpp:(.text+0x1966): undefined reference to `std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>)'
discord_rpc.cpp:(.text+0x19e1): undefined reference to `std::__throw_system_error(int)'
discord_rpc.cpp:(.text+0x19f1): undefined reference to `std::terminate()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_UpdateConnection()':
discord_rpc.cpp:(.text+0x1a57): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text+0x1aa5): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x1aad): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x1aba): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x26f4): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x2cc8): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text+0x2d38): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x2de0): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x2e2c): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x2e34): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x2e41): undefined reference to `operator delete(void*)'
discord_rpc.cpp:(.text+0x371b): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_Initialize::{lambda(int, char const*)#2}::_FUN(int, char const*)':
discord_rpc.cpp:(.text+0x38c4): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text+0x38ed): undefined reference to `std::__throw_system_error(int)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_UpdatePresence':
discord_rpc.cpp:(.text+0x155): undefined reference to `std::condition_variable::notify_all()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_ClearPresence':
discord_rpc.cpp:(.text+0x202): undefined reference to `std::condition_variable::notify_all()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `Discord_Respond':
discord_rpc.cpp:(.text+0x2ca): undefined reference to `std::condition_variable::notify_all()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::~_Sp_counted_base()':
discord_rpc.cpp:(.text._ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EED0Ev[_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EED0Ev]+0x8): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::_Sp_counted_ptr_inplace<std::thread::_Impl<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >, std::allocator<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >, (__gnu_cxx::_Lock_policy)2>::~_Sp_counted_ptr_inplace()':
discord_rpc.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EED0Ev[_ZNSt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EED0Ev]+0x8): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::_Sp_counted_ptr_inplace<std::thread::_Impl<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >, std::allocator<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >, (__gnu_cxx::_Lock_policy)2>::_M_destroy()':
discord_rpc.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EE10_M_destroyEv[_ZNSt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EE10_M_destroyEv]+0x8): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::thread::_Impl_base::~_Impl_base()':
discord_rpc.cpp:(.text._ZNSt6thread10_Impl_baseD0Ev[_ZNSt6thread10_Impl_baseD0Ev]+0x3e): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::thread::_Impl<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >::~_Impl()':
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEED0Ev[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEED0Ev]+0x3e): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:discord_rpc.cpp:(.text._ZN12JsonDocumentD2Ev[_ZN12JsonDocumentD5Ev]+0x51): more undefined references to `operator delete(void*)' follow
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `std::thread::_Impl<std::_Bind_simple<IoThreadHolder::Start()::{lambda()#1} ()> >::_M_run()':
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0x50): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0x93): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0xbd): undefined reference to `std::__throw_system_error(int)'
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0xc4): undefined reference to `std::__throw_system_error(int)'
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0xf0): undefined reference to `std::chrono::_V2::system_clock::now()'
discord_rpc.cpp:(.text._ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv[_ZNSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEE6_M_runEv]+0x132): undefined reference to `std::chrono::_V2::system_clock::now()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o: In function `_GLOBAL__sub_I_Discord_Initialize':
discord_rpc.cpp:(.text.startup+0x102): undefined reference to `std::chrono::_V2::system_clock::now()'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTISt11_Mutex_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTISt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTINSt6thread10_Impl_baseE[_ZTINSt6thread10_Impl_baseE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEE[_ZTINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTISt19_Sp_make_shared_tag[_ZTISt19_Sp_make_shared_tag]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTISt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EE[_ZTISt23_Sp_counted_ptr_inplaceINSt6thread5_ImplISt12_Bind_simpleIFZN14IoThreadHolder5StartEvEUlvE_vEEEESaIS7_ELN9__gnu_cxx12_Lock_policyE2EE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTVSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTVSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x20): undefined reference to `__cxa_pure_virtual'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTVSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE[_ZTVSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE]+0x30): undefined reference to `__cxa_pure_virtual'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.rodata._ZTVNSt6thread10_Impl_baseE[_ZTVNSt6thread10_Impl_baseE]+0x20): undefined reference to `__cxa_pure_virtual'
obj-unix/release/deps/discord-rpc/src/discord_rpc.o:(.eh_frame+0x1ff): undefined reference to `__gxx_personality_v0'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `RpcConnection::Read(JsonDocument&)':
rpc_connection.cpp:(.text+0x42c): undefined reference to `operator delete(void*)'
rpc_connection.cpp:(.text+0x5d6): undefined reference to `operator delete(void*)'
rpc_connection.cpp:(.text+0xae7): undefined reference to `operator delete(void*)'
rpc_connection.cpp:(.text+0xc12): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `RpcConnection::Open()':
rpc_connection.cpp:(.text+0x11b0): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o:rpc_connection.cpp:(.text+0x11f0): more undefined references to `operator delete(void*)' follow
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, FixedLinearAllocator<2048ul> >::EndArray(unsigned int)':
rpc_connection.cpp:(.text._ZN9rapidjson15GenericDocumentINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEE20FixedLinearAllocatorILm2048EEE8EndArrayEj[_ZN9rapidjson15GenericDocumentINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEE20FixedLinearAllocatorILm2048EEE8EndArrayEj]+0x13b): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::GenericValue(char const*, unsigned int, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>&)':
rpc_connection.cpp:(.text._ZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEEC2EPKcjRS5_[_ZN9rapidjson12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEEC5EPKcjRS5_]+0x144): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>::Malloc(unsigned long)':
rpc_connection.cpp:(.text._ZN9rapidjson19MemoryPoolAllocatorINS_12CrtAllocatorEE6MallocEm[_ZN9rapidjson19MemoryPoolAllocatorINS_12CrtAllocatorEE6MallocEm]+0xa6): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `void rapidjson::internal::Stack<FixedLinearAllocator<2048ul> >::Expand<rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > >(unsigned long)':
rpc_connection.cpp:(.text._ZN9rapidjson8internal5StackI20FixedLinearAllocatorILm2048EEE6ExpandINS_12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEEEEEvm[_ZN9rapidjson8internal5StackI20FixedLinearAllocatorILm2048EEE6ExpandINS_12GenericValueINS_4UTF8IcEENS_19MemoryPoolAllocatorINS_12CrtAllocatorEEEEEEEvm]+0xdb): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o: In function `void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, FixedLinearAllocator<2048ul> >::ParseValue<1u, rapidjson::GenericInsituStringStream<rapidjson::UTF8<char> >, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, FixedLinearAllocator<2048ul> > >(rapidjson::GenericInsituStringStream<rapidjson::UTF8<char> >&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>, FixedLinearAllocator<2048ul> >&)':
rpc_connection.cpp:(.text._ZN9rapidjson13GenericReaderINS_4UTF8IcEES2_20FixedLinearAllocatorILm2048EEE10ParseValueILj1ENS_25GenericInsituStringStreamIS2_EENS_15GenericDocumentIS2_NS_19MemoryPoolAllocatorINS_12CrtAllocatorEEES4_EEEEvRT0_RT1_[_ZN9rapidjson13GenericReaderINS_4UTF8IcEES2_20FixedLinearAllocatorILm2048EEE10ParseValueILj1ENS_25GenericInsituStringStreamIS2_EENS_15GenericDocumentIS2_NS_19MemoryPoolAllocatorINS_12CrtAllocatorEEES4_EEEEvRT0_RT1_]+0xea1): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/rpc_connection.o:(.eh_frame+0x32b): undefined reference to `__gxx_personality_v0'
obj-unix/release/deps/discord-rpc/src/serialization.o: In function `JsonWriteUnsubscribeCommand(char*, unsigned long, int, char const*)':
serialization.cpp:(.text+0xd11): undefined reference to `operator delete(void*)'
serialization.cpp:(.text+0x121c): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/serialization.o: In function `JsonWriteSubscribeCommand(char*, unsigned long, int, char const*)':
serialization.cpp:(.text+0x1801): undefined reference to `operator delete(void*)'
serialization.cpp:(.text+0x1d0c): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/serialization.o: In function `JsonWriteJoinReply(char*, unsigned long, char const*, int, int)':
serialization.cpp:(.text+0x2836): undefined reference to `operator delete(void*)'
obj-unix/release/deps/discord-rpc/src/serialization.o:serialization.cpp:(.text+0x2dc1): more undefined references to `operator delete(void*)' follow
obj-unix/release/deps/discord-rpc/src/serialization.o: In function `void rapidjson::internal::Stack<FixedLinearAllocator<2048ul> >::Expand<rapidjson::Writer<DirectStringBuffer, rapidjson::UTF8<char>, rapidjson::UTF8<char>, FixedLinearAllocator<2048ul>, 0u>::Level>(unsigned long)':
serialization.cpp:(.text._ZN9rapidjson8internal5StackI20FixedLinearAllocatorILm2048EEE6ExpandINS_6WriterI18DirectStringBufferNS_4UTF8IcEES9_S3_Lj0EE5LevelEEEvm[_ZN9rapidjson8internal5StackI20FixedLinearAllocatorILm2048EEE6ExpandINS_6WriterI18DirectStringBufferNS_4UTF8IcEES9_S3_Lj0EE5LevelEEEvm]+0xdb): undefined reference to `operator new(unsigned long)'
obj-unix/release/deps/discord-rpc/src/serialization.o:(.eh_frame+0x1b3): undefined reference to `__gxx_personality_v0'
collect2: error: ld returned 1 exit status
make: *** [retroarch] Error 1

### Steps to reproduce the bug

make clean
./configure
make

### Bisect Results

27c2c6c6d733f346a122106888531c62f5f2ca8d is the first bad commit
commit 27c2c6c6d733f346a122106888531c62f5f2ca8d
Author: twinaphex <libretro@gmail.com>
Date:   Wed Aug 8 07:32:37 2018 +0200

    Add Discord integration

:040000 040000 8d129c29a1253e3ba793a59e293bf23ac0a3abdb 1cd0eec676a40bd61f83597087f5679dc0f79182 M      qb
bisect run success

### Version/Commit

- RetroArch: 6001c7f

### Environment information

- OS: Ubuntu 14.04.5 LTS
- Compiler: GNU Make 3.81

**Comment by bparker06** [comment]
Hi @felinben,

Your compiler is too old for the Discord integration. You can get up to gcc 8 with this PPA: https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/test?field.series_filter=trusty

**Comment by twinaphex** [comment]
I do think it sucks horribly that C++ is so inherently nonportable that people need to target specific compilers in order to get basic code to compile.

Ideally, we come up with some C implementation of discord-rpc so that we no longer require certain bumped-up compilers for building RetroArch out of the box. We never required this in the project's lifetime and I think it's an especially bad idea if we start requiring it now.

For now @felinben , you could always opt to bake out Discord support by running configure like this -

./configure --disable-discord.

**Comment by bparker06** [comment]
Curious... what version is your compiler? Because I just tried gcc 4.8 on Ubuntu14 myself and it built fine.

**Comment by RobLoach** [comment]
Fails on Travis's gcc and clang too. I see three options...

1. Update gcc as mentioned by bparker
2. Move to a C implementation as twin mentioned
3. Have Discord disabled by default, and allow it to be enabled with `./configure --enable-discord`

**Comment by felinben** [comment]
@twinaphex disabling discord keeps my boat floating. Thanks!
@bparker06 gcc (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
@RobLoach As a regular block who pulls and compiles almost daily I would go for option 3 because it is an easy fix. I tried installing multiple versions of gcc in the past...I have not kept a very good memory of the whole experience. Will give another try though.

**Comment by bparker06** [comment]
Ok so it looks like it's not the compiler. 9221e4e should fix this issue now. We just weren't using a C++ linker and you didn't have any other features enabled that also turn it on (like Qt, vulkan/slang/etc.).

**Comment by bparker06** [comment]
@RobLoach That commit should also fix Travis.
