### ISSUE TITLE
Current RetroArch cannot build with the menu disabled

### ISSUE THREAD

**Issue by kwyxz** [libretro/RetroArch#16880]
## Description

While troubleshooting a Haiku issue, I noticed that running `./configure --disable-menu` unfortunately does not allow RetroArch to build. This is not Haiku-specific and also happens on Linux (and I am assuming on most, if not all, archs)

### Expected behavior

RetroArch should build, albeit with the menu disabled.

### Actual behavior

```
CC retroarch.c
retroarch.c: In function ‘command_event’:
retroarch.c:4469:46: warning: implicit declaration of function ‘menu_state_get_ptr’; did you mean ‘uico_state_get_ptr’? [-Wimplicit-function-declaration]
 4469 |             struct menu_state *menu_st     = menu_state_get_ptr();
      |                                              ^~~~~~~~~~~~~~~~~~
      |                                              uico_state_get_ptr
retroarch.c:4469:46: warning: initialization of ‘struct menu_state *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
retroarch.c:4528:26: error: invalid use of undefined type ‘struct menu_state’
 4528 |                   menu_st->flags                  |= MENU_ST_FLAG_ENTRIES_NEED_REFRESH;
      |                          ^~
retroarch.c:4528:54: error: ‘MENU_ST_FLAG_ENTRIES_NEED_REFRESH’ undeclared (first use in this function)
 4528 |                   menu_st->flags                  |= MENU_ST_FLAG_ENTRIES_NEED_REFRESH;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
retroarch.c:4528:54: note: each undeclared identifier is reported only once for each function it appears in
retroarch.c:4529:30: error: invalid use of undefined type ‘struct menu_state’
 4529 |                   if (menu_st->driver_ctx->environ_cb)
      |                              ^~
retroarch.c:4530:29: error: invalid use of undefined type ‘struct menu_state’
 4530 |                      menu_st->driver_ctx->environ_cb(MENU_ENVIRON_RESET_HORIZONTAL_LIST,
      |                             ^~
retroarch.c:4530:54: error: ‘MENU_ENVIRON_RESET_HORIZONTAL_LIST’ undeclared (first use in this function)
 4530 |                      menu_st->driver_ctx->environ_cb(MENU_ENVIRON_RESET_HORIZONTAL_LIST,
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
retroarch.c:4531:41: error: invalid use of undefined type ‘struct menu_state’
 4531 |                            NULL, menu_st->userdata);
      |                                         ^~
make: *** [Makefile:209: obj-unix/release/retroarch.o] Error 1
```

### Steps to reproduce the bug

1. git clone the latest version of RA
2. `./configure --disable-menu`
3. `make`

### Bisect Results

According to @sonninnos this was possibly introduced in 87b9d0328e0 but there are various errors at various stages.
I have a pull request ready that will allow building with `--disable-menu --disable-cheevos --disable-qt --disable-slang` but not `--disable-menu` alone.

### Version/Commit

- RetroArch: a759e601484c2202a6a3460b4dd5de708bb41821

### Environment information

- OS: Debian GNU/Linux / Haiku
- Compiler: gcc 12.2.0 / gcc 13.3.0

**Comment by kwyxz** [comment]
Update : I think I re-added cheevos in https://github.com/libretro/RetroArch/pull/16881/commits/8349a48f1d7ca8477f9c147e315c0dfccb8270f6

So now the bug could be solved by just automatically disabling QT when configuring with `--disable-menu`

**Comment by gouchi** [comment]
@kwyxz This issue should be closed per #16881 ? Thank you.

**Comment by kwyxz** [comment]
Even with #16881 merged, `—disable-menu` by itself won’t allow RA to build and requires `—disable-qt`. Ideally the former should imply the latter but after looking at the configure script I am not sure about the best way to proceed.

**Comment by gouchi** [comment]
You are right,  I forgot about `--disable-qt` !

So the idea would be to add something like `add_opt QT no`  maybe around this bloc [config.libs.sh](https://github.com/libretro/RetroArch/blob/fa0e6cc3ff51ae9169f5c12e979dbe310668713e/qb/config.libs.sh#L565-L590) ?

**Comment by kwyxz** [comment]
Possibly, I have been too scared to touch the configuration scripts to be honest :sweat_smile:

**Comment by gouchi** [comment]
Using this patch

```
diff --git a/qb/config.libs.sh b/qb/config.libs.sh
index 06ca062f0c..3eb945a6b3 100644
--- a/qb/config.libs.sh
+++ b/qb/config.libs.sh
@@ -283,22 +283,23 @@ check_enabled CXX DISCORD discord 'The C++ compiler is' false
 check_enabled CXX QT 'Qt companion' 'The C++ compiler is' false
 
 if [ "$HAVE_QT" != 'no' ]; then
-   check_pkgconf QT5CORE Qt5Core 5.2
-   check_pkgconf QT5GUI Qt5Gui 5.2
-   check_pkgconf QT5WIDGETS Qt5Widgets 5.2
-   check_pkgconf QT5CONCURRENT Qt5Concurrent 5.2
-   check_pkgconf QT5NETWORK Qt5Network 5.2
-   #check_pkgconf QT5WEBENGINE Qt5WebEngine 5.4
-
-   # pkg-config is needed to reliably find Qt5 libraries.
-
-   check_enabled QT5CORE QT Qt 'Qt5Core is' true
-   check_enabled QT5GUI QT Qt 'Qt5GUI is' true
-   check_enabled QT5WIDGETS QT Qt 'Qt5Widgets is' true
-   check_enabled QT5CONCURRENT QT Qt 'Qt5Concurrent is' true
-   check_enabled QT5NETWORK QT Qt 'Qt5Network is' true
-   #check_enabled QT5WEBENGINE QT Qt 'Qt5Webengine is' true
-
+   if [ "$HAVE_MENU" != 'no' ]; then
+      check_pkgconf QT5CORE Qt5Core 5.2
+      check_pkgconf QT5GUI Qt5Gui 5.2
+      check_pkgconf QT5WIDGETS Qt5Widgets 5.2
+      check_pkgconf QT5CONCURRENT Qt5Concurrent 5.2
+      check_pkgconf QT5NETWORK Qt5Network 5.2
+      #check_pkgconf QT5WEBENGINE Qt5WebEngine 5.4
+
+      # pkg-config is needed to reliably find Qt5 libraries.
+
+      check_enabled QT5CORE QT Qt 'Qt5Core is' true
+      check_enabled QT5GUI QT Qt 'Qt5GUI is' true
+      check_enabled QT5WIDGETS QT Qt 'Qt5Widgets is' true
+      check_enabled QT5CONCURRENT QT Qt 'Qt5Concurrent is' true
+      check_enabled QT5NETWORK QT Qt 'Qt5Network is' true
+      #check_enabled QT5WEBENGINE QT Qt 'Qt5Webengine is' true
+   fi
    if [ "$HAVE_QT" != yes ]; then
       die : 'Notice: Qt support disabled, required libraries were not found.'
    fi
@@ -587,6 +588,9 @@ if [ "$HAVE_MENU" != 'no' ]; then
       fi
       die : 'Notice: Hardware rendering context not available.'
    fi
+else
+   add_opt QT no
+   die : 'Notice: Qt support disabled, because menu is disabled.'
 fi
 
 if [ "$HAVE_STEAM" = 'yes' ]; then
```
If I use `./configure --disable-menu` I got

`Notice: Qt support disabled, required libraries were not found.`

And if you try `./configure --disable-menu --enable-qt`

```
Notice: Qt support disabled, because menu is disabled.

Checking for moc ... /usr/bin/moc does not work
Warning: moc not found, Qt companion support will be disabled.
```

**Comment by viachaslavic** [comment]
Still getting error from `master`

```cc
CC gfx/video_driver.c
CC tasks/task_pl_thumbnail_download.c
tasks/task_pl_thumbnail_download.c: In function 'task_push_pl_entry_thumbnail_download':
tasks/task_pl_thumbnail_download.c:909:7: error: implicit declaration of function 'runloop_msg_queue_push'; did you mean 'msg_queue_push'? [-Wimplicit-function-declaration]
  909 |       runloop_msg_queue_push(
      |       ^~~~~~~~~~~~~~~~~~~~~~
      |       msg_queue_push
make: *** [Makefile:209: obj-unix/debug/tasks/task_pl_thumbnail_download.o] Error 1
make: *** Waiting for unfinished jobs....
gfx/video_driver.c: In function 'video_driver_frame':
gfx/video_driver.c:3765:45: error: 'MENU_ST_FLAG_ALIVE' undeclared (first use in this function)
 3765 |             && !(video_info.menu_st_flags & MENU_ST_FLAG_ALIVE)
      |                                             ^~~~~~~~~~~~~~~~~~
gfx/video_driver.c:3765:45: note: each undeclared identifier is reported only once for each function it appears in
gfx/video_driver.c:3618:16: warning: variable 'last_frame_duped' set but not used [-Wunused-but-set-variable]
 3618 |    static bool last_frame_duped   = true;
      |                ^~~~~~~~~~~~~~~~
make: *** [Makefile:209: obj-unix/debug/gfx/video_driver.o] Error 1
```

**Comment by gouchi** [comment]
@viachaslavic Indeed, I reproduce the issue using [2a56a82](https://github.com/libretro/RetroArch/tree/2a56a827e8a97a3838a9d455f1dca442c0ffbb07) with `./configure --disable-menu --disable-qt`

@sonninnos It seems we need to add `#if HAVE_MENU`  for [gfx/video_driver.c:3765](https://github.com/libretro/RetroArch/blob/2a56a827e8a97a3838a9d455f1dca442c0ffbb07/gfx/video_driver.c#L3765) ? [Source commit](https://github.com/libretro/RetroArch/commit/391b46c3bea#diff-c472fd8035b6f9434ed083c646b0a687430f9d8b9f3f6bc3c13ae03b6d1eca0c)

Thank you.

**Comment by sonninnos** [comment]
Whoops, on it.

**Comment by sonninnos** [comment]
Disabled menu build was again broken, but I fixed it and also a few other things I noticed. Widget background color is still broken with certain drivers, and I'll save that for later. But surely this can be closed for now.
