### PR TITLE
Correctly fixes --disable-menu.

### PR DESCRIPTION
**Pull request by orbea**
## Description

Correctly fixes `--disable-menu`.

Note that despite its name we want to build `menu_shader.c` with `--disable-menu` and this was done intentionally by @bparker06 when this was first fixed.

## Related Issues

```
LD retroarch
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::getShaders(video_shader**, video_shader**)':
shaderparamsdialog.cpp:(.text+0xaa3): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onFilterComboBoxIndexChanged(int)':
shaderparamsdialog.cpp:(.text+0xb41): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onScaleComboBoxIndexChanged(int)':
shaderparamsdialog.cpp:(.text+0xd01): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderPassMoveDownClicked()':
shaderparamsdialog.cpp:(.text+0xf08): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderPassMoveUpClicked()':
shaderparamsdialog.cpp:(.text+0x1338): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o:shaderparamsdialog.cpp:(.text+0x1743): more undefined references to `menu_shader_get' follow
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderLoadPresetClicked()':
shaderparamsdialog.cpp:(.text+0x1b7d): undefined reference to `menu_shader_manager_set_preset'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderResetPass(int)':
shaderparamsdialog.cpp:(.text+0x1de5): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderResetParameter(QString)':
shaderparamsdialog.cpp:(.text+0x20fe): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderResetAllPasses()':
shaderparamsdialog.cpp:(.text+0x22e6): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderAddPassClicked()':
shaderparamsdialog.cpp:(.text+0x2501): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::saveShaderPreset(char const*, unsigned int)':
shaderparamsdialog.cpp:(.text+0x2f17): undefined reference to `menu_shader_manager_save_preset'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderClearAllPassesClicked()':
shaderparamsdialog.cpp:(.text+0x2faf): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onShaderRemovePassClicked()':
shaderparamsdialog.cpp:(.text+0x3047): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::buildLayout()':
shaderparamsdialog.cpp:(.text+0x31dd): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::addShaderParam(video_shader_parameter*, QFormLayout*)':
shaderparamsdialog.cpp:(.text+0x5759): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o: in function `ShaderParamsDialog::onGroupBoxContextMenuRequested(QPoint const&)':
shaderparamsdialog.cpp:(.text+0x64eb): undefined reference to `menu_shader_get'
/usr/bin/ld: obj-unix/release/ui/drivers/qt/shaderparamsdialog.o:shaderparamsdialog.cpp:(.text+0x6880): more undefined references to `menu_shader_get' follow
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:199: retroarch] Error 1
```

## Related Pull Requests

Broken in d2893d991ce06dbb7ff510b29e96e7e13c30abcb.

### CODE REVIEW

**Comment by orbea** [comment]
Travis confirms the `--disable-menu` build succeeds now, the xcode10.1 build still fails, but that is unrelated to this change.
