### ISSUE TITLE
[Win64] Crash of latest retroarch nightly.

### ISSUE THREAD

**Issue by ofry** [libretro/RetroArch#4402]
retroarch.cfg:

https://www.dropbox.com/s/7fjrjsozc1on1wy/retroarch.cfg?dl=0

**Comment by ofry** [comment]
Both 2017-01-13 and 2017-01-14 versions affected.

**Comment by twinaphex** [comment]
@fr500 Try to see if you can reproduce this.

BTW, just posting a retroarch.cfg is not helping me very much. At least try to come up with a stacktrace, this is pretty much like trying to find a needle in a haystack this way.

**Comment by ofry** [comment]
https://www.dropbox.com/s/88c3u3bfihtzfw5/gdb_log.txt?dl=0

GDB log

**Comment by twinaphex** [comment]
Seems like it's a shader-related issue.

@loganmc10, could I invite you to take a look at this?

**Comment by retro-wertz** [comment]
are you by any chance using a 32bit build? coz i dont see a 1-14-2016 build
for x86_64

i did test the 1-13-2016 build and no crash - it is probably shader issue
as twinaphex said.

**Comment by ofry** [comment]
I edited my comment about versions.

**Comment by ofry** [comment]
retroarch.glslp:

https://www.dropbox.com/s/ndcxjswn4whgesd/retroarch.glslp?dl=0

**Comment by loganmc10** [comment]
I tested that glslp on Linux and it worked, so it's probably some interaction between something in the retroarch.cfg and the shaders. @ofry can you try with a clean retroarch.cfg and maybe narrow it down to what option is causing the crash?

**Comment by ofry** [comment]
> video_threaded = "true"

if I set it to false => all OK.
true => crash.

**Comment by fr500** [comment]
Ok this is an issue but... why are you using video_threaded on PC?

**Comment by ofry** [comment]
While I set that "heavy" shader queue, I got slowdown if video_threaded is false.

GPU: AMD Radeon R7 360 series
CPU: Intel Core i7 3930K

**Comment by iOS4all** [comment]
Sorry to write this here. But please can any one help to get retroarch working on jailbroken iOS 10 please?
I tried but it always said there's no core any help please?

**Comment by fr500** [comment]
@iOS4all open your own issue.
I already asked you not to do this.

This has nothing to do with iOS . This is a development bug tracker not forum.

**Comment by iOS4all** [comment]
Ok thank you very much.

**Comment by twinaphex** [comment]
Removed the distraction which had nothing to do with the subject at hand.

**Comment by ofry** [comment]
GDB log of Retroarch 1.4.0 Windows x64:

https://www.dropbox.com/s/98yzxpqdf7m6ql6/gdb_log_retroarch_15.01.2017.txt?dl=0

**Comment by twinaphex** [comment]
Do a bisect, this is really not helping us out whatsoever.

**Comment by twinaphex** [comment]
Can you unset the shader preset and see if it still happens then? Maybe it's just a bad shader pass.

**Comment by ofry** [comment]
> video_shader_enable = "false"

Crashed again.

**Comment by twinaphex** [comment]
Alright, do a bisect. I can't reproduce your issue, and I don't think radius can either.

**Comment by ofry** [comment]
db6fba51c357a937a423be8aef7c2ce760790578

last good commit.

After it - some commits doesn't compile at all...

db725155c1f3a51de4bab0a2ccc7cb86c5c6a314 - compiled, but same behavior as latest nightly.

**Comment by twinaphex** [comment]
Tell me what the error is that prevents it to compile - you'll have to do some manual local changes then to test each compile.

**Comment by twinaphex** [comment]
Based on your good/bad commits - this seems to be the only possible way it could crash -

https://github.com/libretro/RetroArch/commit/4a9ca6638970ec3c628affb045f2af19ac687872

Test if it's fixed after the latest commit.

**Comment by ofry** [comment]
`gfx/drivers_context/d3d_ctx.cpp: In function 'void gfx_ctx_d3d_input_driver(void                                                                                                                                                                                               *, const char*, const input_driver_t**, void**)':
gfx/drivers_context/d3d_ctx.cpp:192:45: error: 'joypad_name' was not declared in                                                                                                                                                                                                this scope
    dinput               = input_dinput.init(joypad_name);
                                             ^~~~~~~~~~~
make: *** [Makefile:152: obj-unix/gfx/drivers_context/d3d_ctx.o] Ошибка 1
`

**Comment by retro-wertz** [comment]
fixed https://github.com/libretro/RetroArch/commit/b5403da862e65af711b0d217d160d3897d77e096

**Comment by ofry** [comment]
Segfaulted again :( Will try to give gdb log.

**Comment by twinaphex** [comment]
You need to start testing each commit then and telling me what it doesn't compile on, we cannot play whack-a-mole like this, I need you to test each of those commits which didn't compile for you but fix it up locally so that you can test each commit.

**Comment by ofry** [comment]
```
Thread 3 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 8308.0x50ec]
0x000000000051888a in thread_get_current_shader (data=0x665c430)
    at gfx/video_thread_wrapper.c:1250
1250       return thr->poke->get_current_shader(thr->driver_data);

```

OK. I will start to give you compile errors in commits between good and segfaulted.

**Comment by ofry** [comment]
Commit 8bd12368ef56776fd9deb62ae58b51fa3612e1f8

```
CXX gfx/drivers_context/wgl_ctx.cpp
gfx/drivers_context/wgl_ctx.cpp: In function 'void gfx_ctx_wgl_input_driver(void*, const input_driver_t**, void**)':
gfx/drivers_context/wgl_ctx.cpp:564:37: error: too few arguments to function
    dinput_wgl   = input_dinput.init();
                                     ^
make: *** [Makefile:152: obj-unix/gfx/drivers_context/wgl_ctx.o] Ошибка 1

```

**Comment by ofry** [comment]
Commit 0b03e95d952b715776638e81557974f2161113cd

```
CXX gfx/drivers_context/wgl_ctx.cpp
gfx/drivers_context/wgl_ctx.cpp: In function 'void gfx_ctx_wgl_input_driver(void*, const input_driver_t**, void**)':
gfx/drivers_context/wgl_ctx.cpp:564:37: error: too few arguments to function
    dinput_wgl   = input_dinput.init();
                                     ^
make: *** [Makefile:152: obj-unix/gfx/drivers_context/wgl_ctx.o] Ошибка 1
```

**Comment by ofry** [comment]
Commit 76ae7ac4a0ad220b112ff6204e21ca1d3397ada5

```
CXX gfx/drivers_context/wgl_ctx.cpp
gfx/drivers_context/wgl_ctx.cpp: In function 'void gfx_ctx_wgl_input_driver(void*, const input_driver_t**, void**)':
gfx/drivers_context/wgl_ctx.cpp:564:37: error: too few arguments to function
    dinput_wgl   = input_dinput.init();
                                     ^
make: *** [Makefile:152: obj-unix/gfx/drivers_context/wgl_ctx.o] Ошибка 1

```

**Comment by ofry** [comment]
Commit a835149f6987ef1576380e7454c1c08246b61f5b

```
gfx/drivers_context/wgl_ctx.cpp: In function 'void gfx_ctx_wgl_input_driver(void*, const input_driver_t**, void**)':
gfx/drivers_context/wgl_ctx.cpp:562:4: error: 'settings_t' was not declared in this scope
    settings_t *settings = config_get_ptr();
    ^~~~~~~~~~
gfx/drivers_context/wgl_ctx.cpp:562:16: error: 'settings' was not declared in this scope
    settings_t *settings = config_get_ptr();
                ^~~~~~~~
gfx/drivers_context/wgl_ctx.cpp:562:42: error: 'config_get_ptr' was not declared in this scope
    settings_t *settings = config_get_ptr();
                                          ^
make: *** [Makefile:152: obj-unix/gfx/drivers_context/wgl_ctx.o] Ошибка 1
```

**Comment by retro-wertz** [comment]
what is exactly the problem? i thought it was just compiling the latest nightly a few hours ago. how exactly are you compiling on each commit? seems like you never run "./configure and make clean"

in any case, remove video_filter and video_shader (comment them to ="") from your retroarch.cfg or just delete retroarch.cfg and just reconfigure everything when you can finally get retroarch to load. 

go IRC and i can probably be of help.

**Comment by ofry** [comment]
exastly problem is:

1) delete retroarch.cfg - all loads fine.
2) set video_threaded ON, all fine.
3) Close RA.
4) Start RA again. Segfault.

**Comment by ofry** [comment]
Commit da244c177b9721e601214159ffc21b714f13b821

```
gfx/drivers_context/wgl_ctx.cpp: In function 'void gfx_ctx_wgl_input_driver(void*, const input_driver_t**, void**)':
gfx/drivers_context/wgl_ctx.cpp:562:4: error: 'settings_t' was not declared in this scope
    settings_t *settings = config_get_ptr();
    ^~~~~~~~~~
gfx/drivers_context/wgl_ctx.cpp:562:16: error: 'settings' was not declared in this scope
    settings_t *settings = config_get_ptr();
                ^~~~~~~~
gfx/drivers_context/wgl_ctx.cpp:562:42: error: 'config_get_ptr' was not declared in this scope
    settings_t *settings = config_get_ptr();
                                          ^
make: *** [Makefile:152: obj-unix/gfx/drivers_context/wgl_ctx.o] Ошибка 1
```

**Comment by AlexFolland** [comment]
I've reproduced this using the steps by @ofry listed 2 posts above.  I ran it in gdb and got a backtrace.  Here's the backtrace.

```(gdb) r
Starting program: G:\tools\retroarch\retroarch_debug-lex.exe -v --log-file output.log
[New Thread 7264.0x1f10]
[New Thread 7264.0xae8]
[New Thread 7264.0x1c8c]
[New Thread 7264.0x15f8]
[New Thread 7264.0xd88]
[Thread 7264.0x15f8 exited with code 0]
[Thread 7264.0xd88 exited with code 0]
[New Thread 7264.0xeb0]
[New Thread 7264.0x1afc]
[Thread 7264.0xeb0 exited with code 0]
[Thread 7264.0x1afc exited with code 0]
[New Thread 7264.0xe10]
[New Thread 7264.0x1bd8]
[New Thread 7264.0x1174]
[New Thread 7264.0x1bb8]
[New Thread 7264.0xf20]
[New Thread 7264.0x1fa0]
[New Thread 7264.0x1cd4]
[New Thread 7264.0x152c]

Thread 3 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 7264.0x1c8c]
0x00000000004dcbb2 in thread_get_current_shader (data=<optimized out>) at gfx/video_thread_wrapper.c:1251
1251       return thr->poke->get_current_shader(thr->driver_data);
(gdb) bt
#0  0x00000000004dcbb2 in thread_get_current_shader (data=<optimized out>) at gfx/video_thread_wrapper.c:1251
#1  0x0000000000446462 in video_shader_driver_get_current_shader (shader=shader@entry=0x848f7d0) at gfx/video_shader_driver.c:113
#2  0x00000000004e46a0 in ShaderDlgWndProc (hwnd=0x250b8a, message=799, wparam=1, lparam=0) at ui/drivers/ui_win32.c:364
#3  0x0000000077b28975 in USER32!GetWindowDC () from C:\windows\system32\user32.dll
#4  0x0000000077b298c2 in USER32!TranslateMessage () from C:\windows\system32\user32.dll
#5  0x00000000004e5d6e in ui_application_win32_process_events () at ui/drivers/win32/ui_win32_application.c:46
#6  0x0000000000692aa1 in win32_check_window (quit=0x848fb36, resize=resize@entry=0x848fb37, width=0x848fb38, height=height@entry=0x848fb3c) at gfx/common/win32_common.cpp:618
#7  0x00000000004f56db in gfx_ctx_wgl_check_window (data=<optimized out>, quit=<optimized out>, resize=0x848fb37, width=<optimized out>, height=0x848fb3c, frame_count=0) at gfx/drivers_context/wgl_ctx.cpp:317
#8  0x00000000004e6103 in video_context_driver_check_window (size_data=size_data@entry=0x848fb40) at gfx/video_context_driver.c:278
#9  0x00000000004e988b in gl_alive (data=0x81100b0) at gfx/drivers/gl.c:2146
#10 0x00000000004dedea in video_thread_loop (data=0x78c8ed0) at gfx/video_thread_wrapper.c:628
#11 0x00000000004dc553 in thread_wrap (data_=0x78c0450) at libretro-common/rthreads/rthreads.c:105
#12 0x0000000077a059cd in KERNEL32!BaseThreadInitThunk () from C:\windows\system32\kernel32.dll
#13 0x0000000077c3a561 in ntdll!RtlUserThreadStart () from C:\windows\SYSTEM32\ntdll.dll
#14 0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)```

**Comment by loganmc10** [comment]
Perhaps this line:

https://github.com/libretro/RetroArch/blob/master/gfx/video_thread_wrapper.c#L1249

Should also check the safety of thr->driver_data

**Comment by AlexFolland** [comment]
With the latest commit, it no longer crashes with threaded video enabled, but it does crash when trying to load a shader preset.  Here's the stack trace.

```Thread 18 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 7356.0x2370]
0x00000000004dcb82 in thread_get_current_shader (data=<optimized out>) at gfx/video_thread_wrapper.c:1251
1251       return thr->poke->get_current_shader(thr->driver_data);
(gdb) bt
#0  0x00000000004dcb82 in thread_get_current_shader (data=<optimized out>) at gfx/video_thread_wrapper.c:1251
#1  0x0000000000446452 in video_shader_driver_get_current_shader (shader=shader@entry=0x868f980) at gfx/video_shader_driver.c:113
#2  0x00000000004e49b1 in shader_dlg_params_reload () at ui/drivers/ui_win32.c:222
#3  0x00000000004ec2af in gl_set_shader (data=0xfab6570, type=<optimized out>, path=<optimized out>) at gfx/drivers/gl.c:2333
#4  0x00000000004ded70 in video_thread_handle_packet (incoming=0x868fc40, thr=0xfa96200) at gfx/video_thread_wrapper.c:413
#5  video_thread_loop (data=0xfa96200) at gfx/video_thread_wrapper.c:591
#6  0x00000000004dc523 in thread_wrap (data_=0x7392290) at libretro-common/rthreads/rthreads.c:105
#7  0x0000000077a059cd in KERNEL32!BaseThreadInitThunk () from C:\windows\system32\kernel32.dll
#8  0x0000000077c3a561 in ntdll!RtlUserThreadStart () from C:\windows\SYSTEM32\ntdll.dll
#9  0x0000000000000000 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb)```

**Comment by AlexFolland** [comment]
This is probably fixed.  I can't reproduce it now.  @ofry can you reproduce it?

**Comment by ofry** [comment]
Yes. It's fixed! Thank you very much!
