### ISSUE TITLE
Compile broken on Pi as of e545d695ecd8c070f1c92d45df8218b60375f154

### ISSUE THREAD

**Issue by ghost** [libretro/RetroArch#750]
Apologies if this is known, or a WIP (as the commit message hints at). Compiling RetroArch on the Raspberry Pi is currently broken - 

```
gfx/vg.c: In function ‘vg_init’:
gfx/vg.c:140:4: error: too few arguments to function ‘font_renderer_create_default’
In file included from gfx/vg.c:30:0:
gfx/fonts/fonts.h:68:6: note: declared here
gfx/vg.c:148:74: error: ‘struct <anonymous>’ has no member named ‘font_scale’
gfx/vg.c: In function ‘vg_render_message’:
gfx/vg.c:215:28: error: storage size of ‘out’ isn’t known
gfx/vg.c:216:19: error: ‘font_renderer_driver_t’ has no member named ‘render_msg’
gfx/vg.c:227:27: error: dereferencing pointer to incomplete type
gfx/vg.c:228:27: error: dereferencing pointer to incomplete type
gfx/vg.c:229:24: error: dereferencing pointer to incomplete type
gfx/vg.c:230:24: error: dereferencing pointer to incomplete type
gfx/vg.c:232:39: error: dereferencing pointer to incomplete type
gfx/vg.c:232:52: error: dereferencing pointer to incomplete type
gfx/vg.c:235:36: error: dereferencing pointer to incomplete type
gfx/vg.c:236:34: error: dereferencing pointer to incomplete type
gfx/vg.c:236:49: error: dereferencing pointer to incomplete type
gfx/vg.c:236:66: error: dereferencing pointer to incomplete type
gfx/vg.c:236:90: error: dereferencing pointer to incomplete type
gfx/vg.c:236:112: error: dereferencing pointer to incomplete type
gfx/vg.c:242:18: error: dereferencing pointer to incomplete type
gfx/vg.c:245:19: error: ‘font_renderer_driver_t’ has no member named ‘free_output’
```

I git bisected it to

```
commit e545d695ecd8c070f1c92d45df8218b60375f154
Author: Themaister <maister@archlinux.us>
Date:   Sat Jun 7 21:18:58 2014 +0200

    Begin big rewrite of GL/raster font rendering path.
```

Cheers.
