### ISSUE TITLE
Build failure with Python3

### ISSUE THREAD

**Issue by orbea** [libretro/RetroArch#4563]
## Description

RetroArch will fail to build with Python3.

### Expected behavior

If this feature is supposed to work (?) it should build. Otherwise it should not be in the configure.

### Actual behavior

```
CC libretro-common/formats/wav/rwav.c
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_input’:
gfx/drivers_tracker/video_state_python.c:111:4: error: unknown type name ‘settings_t’
    settings_t *settings = config_get_ptr();
    ^
gfx/drivers_tracker/video_state_python.c:111:27: warning: implicit declaration of function ‘config_get_ptr’ [-Wimplicit-function-declaration]
    settings_t *settings = config_get_ptr();
                           ^
gfx/drivers_tracker/video_state_python.c:111:27: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
CC menu/drivers/rgui.c
gfx/drivers_tracker/video_state_python.c:114:29: error: request for member ‘input’ in something not a structure or union
       py_binds[i] = settings->input.binds[i];
                             ^
gfx/drivers_tracker/video_state_python.c:125:60: error: incompatible type for argument 2 of ‘current_input->input_state’
       res = current_input->input_state(current_input_data, py_binds,
                                                            ^
gfx/drivers_tracker/video_state_python.c:125:60: note: expected ‘rarch_joypad_info_t {aka struct rarch_joypad_info}’ but argument is of type ‘const struct retro_keybind **’
gfx/drivers_tracker/video_state_python.c:126:13: warning: passing argument 3 of ‘current_input->input_state’ makes pointer from integer without a cast [-Wint-conversion]
             user - 1, RETRO_DEVICE_JOYPAD, 0, key);
             ^
gfx/drivers_tracker/video_state_python.c:126:13: note: expected ‘const struct retro_keybind **’ but argument is of type ‘unsigned int’
gfx/drivers_tracker/video_state_python.c:125:13: error: too few arguments to function ‘current_input->input_state’
       res = current_input->input_state(current_input_data, py_binds,
             ^
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_analog’:
gfx/drivers_tracker/video_state_python.c:134:4: error: unknown type name ‘settings_t’
    settings_t *settings = config_get_ptr();
    ^
gfx/drivers_tracker/video_state_python.c:134:27: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
    settings_t *settings = config_get_ptr();
                           ^
gfx/drivers_tracker/video_state_python.c:138:29: error: request for member ‘input’ in something not a structure or union
       py_binds[i] = settings->input.binds[i];
                             ^
gfx/drivers_tracker/video_state_python.c:148:57: error: incompatible type for argument 2 of ‘current_input->input_state’
    res = current_input->input_state(current_input_data, py_binds,
                                                         ^
gfx/drivers_tracker/video_state_python.c:148:57: note: expected ‘rarch_joypad_info_t {aka struct rarch_joypad_info}’ but argument is of type ‘const struct retro_keybind **’
gfx/drivers_tracker/video_state_python.c:149:10: warning: passing argument 3 of ‘current_input->input_state’ makes pointer from integer without a cast [-Wint-conversion]
          user - 1, RETRO_DEVICE_ANALOG, index, id)
          ^
gfx/drivers_tracker/video_state_python.c:149:10: note: expected ‘const struct retro_keybind **’ but argument is of type ‘unsigned int’
gfx/drivers_tracker/video_state_python.c:148:10: error: too few arguments to function ‘current_input->input_state’
    res = current_input->input_state(current_input_data, py_binds,
          ^
gfx/drivers_tracker/video_state_python.c:150:4: error: expected ‘;’ before ‘retur ’
    return PyFloat_FromDouble((double)res / 0x7fff);
    ^
gfx/drivers_tracker/video_state_python.c:133:12: warning: variable ‘res’ set but not used [-Wunused-but-set-variable]
    int16_t res = 0;
            ^
gfx/drivers_tracker/video_state_python.c: In function ‘py_state_get’:
gfx/drivers_tracker/video_state_python.c:386:4: error: unknown type name ‘settings_t’
    settings_t *settings = config_get_ptr();
    ^
gfx/drivers_tracker/video_state_python.c:386:27: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
    settings_t *settings = config_get_ptr();
                           ^
gfx/drivers_tracker/video_state_python.c:390:53: error: request for member ‘input’ in something not a structure or union
       struct retro_keybind *general_binds = settings->input.binds[i];
                                                     ^
gfx/drivers_tracker/video_state_python.c:391:53: error: request for member ‘input’ in something not a structure or union
       struct retro_keybind *auto_binds    = settings->input.autoconf_binds[i];
                                                     ^
gfx/drivers_tracker/video_state_python.c:392:53: error: request for member ‘input’ in something not a structure or union
       enum analog_dpad_mode dpad_mode     = settings->input.analog_dpad_mode[i];
                                                     ^
CC menu/drivers/materialui.c
gfx/drivers_tracker/video_state_python.c:405:53: error: request for member ‘input’ in something not a structure or union
       struct retro_keybind *general_binds = settings->input.binds[i];
                                                     ^
gfx/drivers_tracker/video_state_python.c:406:53: error: request for member ‘input’ in something not a structure or union
       struct retro_keybind *auto_binds    = settings->input.autoconf_binds[i];
                                                     ^
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_analog’:
gfx/drivers_tracker/video_state_python.c:151:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Makefile:152: obj-unix/gfx/drivers_tracker/video_state_python.o] Error 1
make: *** Waiting for unfinished jobs....
```

### Steps to reproduce the bug

1. `./configure --enable-python && make`

### Bisect Results

```
562c1e996c7e75978d1d189b13513e939f514a79 is the first bad commit
commit 562c1e996c7e75978d1d189b13513e939f514a79
Author: twinaphex <libretro@gmail.com>
Date:   Thu Sep 1 05:38:26 2016 +0200

    Get rid of more header includes

:040000 040000 c2a5949e4433d2a983e186cbb6c8240b50eaa0c4 d1c820e57dd0a0174c94f67d52a2c4b9947ca28b M	gfx
```
562c1e996c7e75978d1d189b13513e939f514a79

As explained in the comment for the commit, some of the issues can be solved with `#include "../../configuration.h"` in video_state_python.c.

### Version/Commit

-`RetroArch-1.4.1-x86_64-1_SBo`
-`python3-3.6.0-x86_64-3_SBo`

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-5.4.0`

**Comment by orbea** [comment]
The `#include "../../configuration.h"` fix worked until commit.
```
8cc5b0942846f42536e6b7a3df294e116caaa2f2 is the first bad commit
commit 8cc5b0942846f42536e6b7a3df294e116caaa2f2
Author: twinaphex <libretro@gmail.com>
Date:   Sun Oct 23 04:38:08 2016 +0200

    Get rid of slow wrapper function input_driver_state

:040000 040000 d4e0e1187ed2e5cb11f8d4488f870aa7e2489c5b a60f578b6f5485c4c7c530b662dc3503bf011389 M	gfx
:040000 040000 78208303c16565f1302ff01900fca01ae3725bd0 c035b6d679e914d9f092b9fbd6c47791bdd9307e M	input
:040000 040000 74b860954a4865e633da9b3e64722100d61fa6b7 e741f8eb5d17e26e39f7fc53da124416f9439609 M	menu
```
8cc5b0942846f42536e6b7a3df294e116caaa2f2

Adding a missing `;` resolves it...

**Comment by orbea** [comment]
The above fixed worked until...
```
d48141041d8b6b298d0fff9d275e1cdd230baf8f is the first bad commit
commit d48141041d8b6b298d0fff9d275e1cdd230baf8f
Author: twinaphex <libretro@gmail.com>
Date:   Tue Jan 10 17:40:21 2017 +0100

    Pass joypad_info to input_state function callback - less
    settings pointer grabbing

:040000 040000 e17ba27ab62a20d95636e09e6926eaea6141af60 ff75a0a4189617eece357d66ed58049a02b20471 M	gfx
:040000 040000 c0424efb6b7b229c822ad57384e8a4980eba9dc0 f4c56bf94e7f912b4f2d6ab5c9c41d6cfc37cc4e M	input
:040000 040000 0d759490e8e1a2a552c66428d71738d89958faaf f2db8762c31c8a6e8f505776203094170840ed37 M	menu
```
d48141041d8b6b298d0fff9d275e1cdd230baf8f
```
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_input’:
gfx/drivers_tracker/video_state_python.c:126:60: error: incompatible type for argument 2 of ‘current_input->input_state’
       res = current_input->input_state(current_input_data, py_binds,
                                                            ^
gfx/drivers_tracker/video_state_python.c:126:60: note: expected ‘rarch_joypad_info_t {aka struct rarch_joypad_info}’ but argument is of type ‘const struct retro_keybind **’
gfx/drivers_tracker/video_state_python.c:127:13: warning: passing argument 3 of ‘current_input->input_state’ makes pointer from integer without a cast [-Wint-conversion]
             user - 1, RETRO_DEVICE_JOYPAD, 0, key);
             ^
gfx/drivers_tracker/video_state_python.c:127:13: note: expected ‘const struct retro_keybind **’ but argument is of type ‘unsigned int’
gfx/drivers_tracker/video_state_python.c:126:13: error: too few arguments to function ‘current_input->input_state’
       res = current_input->input_state(current_input_data, py_binds,
             ^
gfx/drivers_tracker/video_state_python.c: In function ‘py_read_analog’:
gfx/drivers_tracker/video_state_python.c:149:57: error: incompatible type for argument 2 of ‘current_input->input_state’
    res = current_input->input_state(current_input_data, py_binds,
                                                         ^
gfx/drivers_tracker/video_state_python.c:149:57: note: expected ‘rarch_joypad_info_t {aka struct rarch_joypad_info}’ but argument is of type ‘const struct retro_keybind **’
gfx/drivers_tracker/video_state_python.c:150:10: warning: passing argument 3 of ‘current_input->input_state’ makes pointer from integer without a cast [-Wint-conversion]
          user - 1, RETRO_DEVICE_ANALOG, index, id);
          ^
gfx/drivers_tracker/video_state_python.c:150:10: note: expected ‘const struct retro_keybind **’ but argument is of type ‘unsigned int’
gfx/drivers_tracker/video_state_python.c:149:10: error: too few arguments to function ‘current_input->input_state’
    res = current_input->input_state(current_input_data, py_binds,
          ^
CC audio/drivers/alsathread.c
make: *** [Makefile:147: obj-unix/gfx/drivers_tracker/video_state_python.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by twinaphex** [comment]
Should compile again with this -

https://github.com/libretro/RetroArch

**Comment by orbea** [comment]
Thanks! It now builds for me.
