### PR TITLE
fixing cheevos (broken after #6389)

### PR DESCRIPTION
**Pull request by meleu**
## Description

This fixes the cheevos feature, which was broken after PR #6389.

~~In order to make it work I had to declare the function `task_push_http_transfer_generic()` in `tasks/task_http.c` without the `static` modifier.~~

**UPDATE**: I created a function named `task_push_http_transfer_raw()` and made it NOT perform all that encoding url stuff implemented in #6389. And then made `cheevos.c` call the `_raw` version.

## Related Pull Requests

#6389 

## Reviewers

@leiradel @fr500 @RobLoach

### CODE REVIEW

**Comment by meleu** [comment]
Wooops! According to the [Travis CI](https://travis-ci.org/libretro/RetroArch/builds/354138603) it failed to compile for OSX... :(

**Comment by twinaphex** [comment]
Posting the error here for OSX -

In file included from /Users/travis/build/libretro/RetroArch/griffin/griffin.c:1084:
/Users/travis/build/libretro/RetroArch/griffin/../tasks/task_http.c:245:7: error: conflicting types for 'task_push_http_transfer_generic'
void* task_push_http_transfer_generic(
      ^
In file included from /Users/travis/build/libretro/RetroArch/griffin/griffin.c:151:
/Users/travis/build/libretro/RetroArch/griffin/../cheevos/cheevos.c:1909:7: note: previous implicit declaration is here
      task_push_http_transfer_generic(
      ^

**Comment by meleu** [comment]
trying another approach

**Comment by meleu** [comment]
Yeah!

@twinaphex looks like it's ready to go! ;)
