### ISSUE TITLE
[Linux] "Failed to compile vertex shader stage" on second core launch since upgraded to 1.10.0

### ISSUE THREAD

**Issue by TiBeN** [libretro/RetroArch#13583]
## Description

Since i upgraded to RetroArch 1.10, slang shaders do not apply the second time i launch a core (whatever the core, i use a global preset). On the second run there is the following error:

```
[INFO] [Shaders]: Specific shader preset found at "/home/ben/.config/retroarch/config/global.slangp".
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/crt-lottes-multipass-glow.slangp
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/linearize.slang
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/blur_horiz.slang
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/blur_vert.slang
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/threshold.slang
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-lottes-multipass/bloompass.slang
[INFO] Watching file for changes: /home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-lottes-multipass/scanpass-glow.slang
[INFO] [slang]: Compiling shader: "/home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/linearize.slang".
[ERROR] 
[ERROR] [slang]: Failed to compile vertex shader stage.
[ERROR] [Vulkan]: Failed to compile shader: "/home/ben/.config/retroarch/shaders/shaders_slang/crt/shaders/crt-easymode-halation/linearize.slang".
[ERROR] [Vulkan]: Failed to create preset: "/home/ben/.config/retroarch/config/global.slangp".
```

First run after launch retroarch is OK. If i close retroarch, then restart it works again (but on the second run the same error occurs again of course).
To make things simple, i have to quit Retroarch each time i change a core/game to make shaders work again.

### Expected behavior

Slang shaders is applied on every core launch without having to shutdown and restart Retroarch.

### Actual behavior

Shaders do not apply second time a core is run after retroarch is launched.

### Steps to reproduce the bug

(Consider a slang shader preset is configured globally)

1. Start retroarch
2. Launch a content 
3. Notice the shader preset is correctly applied
2. Close content (simple content restart through quick menu does not apply here, content has to be closed)
3. Launch another content (or the same, no matter)
4. Notice this time the shader preset is not applied at all

### Bisect Results

Issue appeared just after upgrading to 1.10 through pacman (archlinux). Previous versions did not have this issue.

### Version/Commit

- RetroArch: 1.10.0 - b71be7efd2

### Environment information

- OS: Archlinux

[Verbose logs of a RA session](https://github.com/libretro/RetroArch/files/7973640/ra-logs.txt)
[retroarch.cfg.txt](https://github.com/libretro/RetroArch/files/7973648/retroarch.cfg.txt)

**Comment by i30817** [comment]
That sounds like it might be a driver shader cache problem. Nvidia has a shader cache on home for linux, ~/nvm or something like that (i moved mine to .cache).

**Comment by TiBeN** [comment]
Looks like the directory is : `~/.cache/mesa_shader_cache`:
<https://unix.stackexchange.com/questions/604737/where-does-mesa-store-its-vulkan-shader-cache-on-linux>

My machine has an intel graphic chip (Iris Xe)

I deleted this dir then tried again. Same behavior:
First run it okay (the dir is recreated and filled), second run fails. I tried to delete this dir in between two runs but issue remains.

I think shaders would not work at all if it was a permission issue. Permissions look correct on my machine:

```
drwx------ 70 ben  ben  4.0K Feb  1 11:11 .cache
```

**Comment by TiBeN** [comment]
Just compiled myself RetroArch v1.9.14:

```
git clone ..
git checkout v1.9.14
```

It works correctly with v1.9.14 so its a regression in v1.10.0

**Comment by TiBeN** [comment]
Ok so i found that compiling retroarch with the following flag is triggering the bug:

```
./configure --disable-builtinglslang
```
This flag is enabled in RetroArch package since v1.10.0-1. I'll report it to the maintainer.

**Comment by nfp0** [comment]
I have this exact same issue on my Radeon RX 6800 on Manjaro Linux (which is Arch based).

**Comment by alucryd** [comment]
We try to avoid builtins as much as possible on Arch, so I'd rather keep using our system glslang if possible. I see no reason why our glslang wouldn't have enough permissions on the first run, but not on subsequent ones. Any ideas?

**Comment by TiBeN** [comment]
@alucryd 
I really have no idea as my knowledge about slang shader etc. are pretty limited on "the dev side". Maybe some kind of "pid" file or tmp file which is not cleaned properly between the two launchs ? ..  

However I can do some tests if it could help. Let me know. Is there some debug environment variables (like mesa vars) which could give more insight about the sader compilation error ?

**Comment by nfp0** [comment]
This only started manifesting specifically on RetroArch 1.10.0 though. Does not happen with previous versions.

**Comment by TiBeN** [comment]
@nfp0 the maintainer fixes (or at least worked-around ) this issue with the new package 1.10.0-3

**Comment by nfp0** [comment]
@TiBeN Sweet. Thanks for the heads-up!

**Comment by alucryd** [comment]
@TiBeN I have no idea how any of this works either, for now I just reinstated the builtin glslang. I would love to hear from the retroarch devs to get some insight on this issue, I'll try to dig the cache lead when I have some time.

**Comment by TiBeN** [comment]
@alucryd i understant. It seems the kind of bug which is pretty hard to diagnose. It could be a pure retroarch bug when the glslang lib is not embedded, it could be the glslang lib in retroarch repository or gslang upstream. To this point it may be interesting to inform glsang maintainers and upstream about this issue ?

**Comment by gouchi** [comment]
@TiBeN Is it still an issue or can we close this issue ? Thank you.

**Comment by TiBeN** [comment]
@gouchi Issue had been solved long time ago at the Archlinux package level if my memory serves me right: <https://bugs.archlinux.org/task/73585>. I don't know if it is a workaround or the issue is fixed. 
At least it is not an issue for me anymore since. So i think it can be closed..

**Comment by hizzlekizzle** [comment]
Ah, looks like it happens if you don't use our vendored slang. Still something we should fix, but not an emergency.
