### ISSUE TITLE
Retroarch no longer compiles on Amlogic S905 on Libreelec after commit c4f8185

### ISSUE THREAD

**Issue by shantigilbert** [libretro/RetroArch#6633]
## Description

Retroarch no longer compiles on Amlogic S905 on Libreelec (same OS that Lakka uses) after commit c4f8185

### Expected behavior

Finish compiling

### Actual behavior

This is the error I get:
```

gfx/drivers_context/mali_fbdev_ctx.c: In function 'gfx_ctx_mali_fbdev_set_video_mode':
gfx/drivers_context/mali_fbdev_ctx.c:183:7: error: 'ctx' undeclared (first use in this function)
       ctx->refresh_rate = 1000000.0f / vinfo.pixclock * 1000000.0f /
       ^~~
gfx/drivers_context/mali_fbdev_ctx.c:183:7: note: each undeclared identifier is reported only once for each function it appears in
gfx/drivers_context/mali_fbdev_ctx.c:184:64: error: called object is not a function or function pointer
          (vinfo.yres + vinfo.upper_margin + vinfo.lower_margin + vinfo.vsync_len)
```

### Steps to reproduce the bug

1. clone repo
2. crosscompile with Libreelec

### Bisect Results
this started happening after this commit
https://github.com/libretro/RetroArch/commit/c4f818599cdb07310095aecc2b9dffe27731eade
before that commit it compiles and works fine

### Version/Commit
You can find this information under Information/System Information

- RetroArch: [version/commit]

### Environment information

- OS: Libreelec for Amlogic
- Compiler: [In case you are running local builds]

**Comment by twinaphex** [comment]
Hi @bearoso, could you help getting this back to work again?

**Comment by bearoso** [comment]
Ok, See #6638.

**Comment by shantigilbert** [comment]
@bearoso @twinaphex Thanks, but after the typo fix I still get this error:

```
gfx/drivers_context/mali_fbdev_ctx.c: In function 'gfx_ctx_mali_fbdev_set_video_mode':
gfx/drivers_context/mali_fbdev_ctx.c:183:64: error: called object is not a function or function pointer
          (vinfo.yres + vinfo.upper_margin + vinfo.lower_margin + vinfo.vsync_len)
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:171: obj-unix/release/gfx/drivers_context/mali_fbdev_ctx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
```

**Comment by bearoso** [comment]
Yeah sorry, it’s missing a division operator at the end of the middle line. I can do a pull request tomorrow, or @twinaphex can just make that change.

**Comment by shantigilbert** [comment]
Thanks, this was fixed with PR #6646
