### ISSUE TITLE
Linux x86_64 build failure

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#10940]
# Actual behavior

```
retroarch.c: In function ‘command_stdin_poll’:
retroarch.c:12811:22: error: ‘p_rarch’ undeclared (first use in this function)
12811 |    command_parse_msg(p_rarch,
      |                      ^~~~~~~
retroarch.c:12811:22: note: each undeclared identifier is reported only once for each function it appears in
Makefile:204: recipe for target 'obj-unix/release/retroarch.o' failed
make: *** [obj-unix/release/retroarch.o] Error 1
```

### Bisect Results

d8824af4ac49d9a9ae36116f9b39e17c3659a99d is the first bad commit

### Environment information

- OS: Linux Mint 19.3 x86_64, kernel 5.3.0
- Compiler: GCC 9.3.0

**Comment by twinaphex** [comment]
Should be fixed now.

**Comment by Sanaki** [comment]
Confirmed fixed.
