### ISSUE TITLE
[Regression] Build fails on GLES only configuration with ffmpeg core

### ISSUE THREAD

**Issue by cmitu** [libretro/RetroArch#19364]
### Is there an existing issue for this?

- [x] This is a bug in RetroArch frontend
- [ ] I have searched the existing issues

### Description

Trying to build `retroarch` with in a GLES2 only configuration results in a build error due to the `ffpmeg_core.c` file requireing OpenGL (core) functions.

This used to work in `v1.22.1`, but not in the current `master`.

Build errors:
```
...

CC cores/libretro-ffmpeg/ffmpeg_core.c
CC libretro-common/rthreads/tpool.c
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_init_quad_vao’:
cores/libretro-ffmpeg/ffmpeg_core.c:1151:4: error: implicit declaration of function ‘glGenVertexArrays’; did you mean ‘glGenVertexArraysOES’? [-Wimplicit-function-declaration]
 1151 |    glGenVertexArrays(1, &fft->vao);
      |    ^~~~~~~~~~~~~~~~~
      |    glGenVertexArraysOES
cores/libretro-ffmpeg/ffmpeg_core.c:1152:4: error: implicit declaration of function ‘glBindVertexArray’; did you mean ‘glBindVertexArrayOES’? [-Wimplicit-function-declaration]
 1152 |    glBindVertexArray(fft->vao);
      |    ^~~~~~~~~~~~~~~~~
      |    glBindVertexArrayOES
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_init_texture’:
cores/libretro-ffmpeg/ffmpeg_core.c:1168:4: error: implicit declaration of function ‘glTexStorage2D’; did you mean ‘glTexStorage2DEXT’? [-Wimplicit-function-declaration]
 1168 |    glTexStorage2D(GL_TEXTURE_2D, levels, format, width, height);
      |    ^~~~~~~~~~~~~~
      |    glTexStorage2DEXT
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_init_target’:
cores/libretro-ffmpeg/ffmpeg_core.c:1184:18: error: ‘GL_RGBA8’ undeclared (first use in this function); did you mean ‘GL_RGBA4’?
 1184 |    if (format == GL_RGBA8)
      |                  ^~~~~~~~
      |                  GL_RGBA4
cores/libretro-ffmpeg/ffmpeg_core.c:1184:18: note: each undeclared identifier is reported only once for each function it appears in
cores/libretro-ffmpeg/ffmpeg_core.c:1189:23: error: ‘GL_RG16I’ undeclared (first use in this function)
 1189 |    else if (format == GL_RG16I)
      |                       ^~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c:1192:7: error: implicit declaration of function ‘glClearBufferiv’ [-Wimplicit-function-declaration]
 1192 |       glClearBufferiv(GL_COLOR, 0, v);
      |       ^~~~~~~~~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c:1192:23: error: ‘GL_COLOR’ undeclared (first use in this function)
 1192 |       glClearBufferiv(GL_COLOR, 0, v);
      |                       ^~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c:1197:7: error: implicit declaration of function ‘glClearBufferuiv’ [-Wimplicit-function-declaration]
 1197 |       glClearBufferuiv(GL_COLOR, 0, v);
      |       ^~~~~~~~~~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_init’:
cores/libretro-ffmpeg/ffmpeg_core.c:1238:46: error: ‘GL_R16UI’ undeclared (first use in this function)
 1238 |    hwfft_init_texture(fft, &fft->window_tex, GL_R16UI,
      |                                              ^~~~~~~~
CC gfx/video_crt_switch.c
cores/libretro-ffmpeg/ffmpeg_core.c:1258:45: error: ‘GL_RG16I’ undeclared (first use in this function)
 1258 |    hwfft_init_texture(fft, &fft->input_tex, GL_RG16I,
      |                                             ^~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c:1260:41: error: ‘GL_RG32UI’ undeclared (first use in this function)
 1260 |    hwfft_init_target(fft, &fft->output, GL_RG32UI,
      |                                         ^~~~~~~~~
cores/libretro-ffmpeg/ffmpeg_core.c:1262:42: error: ‘GL_RGBA8’ undeclared (first use in this function); did you mean ‘GL_RGBA4’?
 1262 |    hwfft_init_target(fft, &fft->resolve, GL_RGBA8,
      |                                          ^~~~~~~~
      |                                          GL_RGBA4
cores/libretro-ffmpeg/ffmpeg_core.c:1285:27: error: ‘GL_RG_INTEGER’ undeclared (first use in this function); did you mean ‘GL_RED_INTEGER’?
 1285 |             fft->size, 1, GL_RG_INTEGER, GL_UNSIGNED_INT, &param_buffer[0]);
      |                           ^~~~~~~~~~~~~
      |                           GL_RED_INTEGER
cores/libretro-ffmpeg/ffmpeg_core.c:1293:17: error: ‘GL_PIXEL_UNPACK_BUFFER’ undeclared (first use in this function); did you mean ‘GL_PIXEL_UNPACK_BUFFER_NV’?
 1293 |    glBindBuffer(GL_PIXEL_UNPACK_BUFFER, fft->pbo);
      |                 ^~~~~~~~~~~~~~~~~~~~~~
      |                 GL_PIXEL_UNPACK_BUFFER_NV
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_init_multisample’:
cores/libretro-ffmpeg/ffmpeg_core.c:1463:7: error: implicit declaration of function ‘glRenderbufferStorageMultisample’; did you mean ‘glRenderbufferStorageMultisampleEXT’? [-Wimplicit-function-declaration]
 1463 |       glRenderbufferStorageMultisample(GL_RENDERBUFFER, samples,
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       glRenderbufferStorageMultisampleEXT
cores/libretro-ffmpeg/ffmpeg_core.c:1464:13: error: ‘GL_RGBA8’ undeclared (first use in this function); did you mean ‘GL_RGBA4’?
 1464 |             GL_RGBA8, width, height);
      |             ^~~~~~~~
      |             GL_RGBA4
cores/libretro-ffmpeg/ffmpeg_core.c:1467:13: error: ‘GL_DEPTH24_STENCIL8’ undeclared (first use in this function); did you mean ‘GL_DEPTH24_STENCIL8_OES’?
 1467 |             GL_DEPTH24_STENCIL8, width, height);
      |             ^~~~~~~~~~~~~~~~~~~
      |             GL_DEPTH24_STENCIL8_OES
cores/libretro-ffmpeg/ffmpeg_core.c:1473:49: error: ‘GL_DEPTH_STENCIL_ATTACHMENT’ undeclared (first use in this function); did you mean ‘GL_STENCIL_ATTACHMENT’?
 1473 |       glFramebufferRenderbuffer(GL_FRAMEBUFFER, GL_DEPTH_STENCIL_ATTACHMENT,
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                 GL_STENCIL_ATTACHMENT
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_step’:
cores/libretro-ffmpeg/ffmpeg_core.c:1528:17: error: ‘GL_PIXEL_UNPACK_BUFFER’ undeclared (first use in this function); did you mean ‘GL_PIXEL_UNPACK_BUFFER_NV’?
 1528 |    glBindBuffer(GL_PIXEL_UNPACK_BUFFER, fft->pbo);
      |                 ^~~~~~~~~~~~~~~~~~~~~~
      |                 GL_PIXEL_UNPACK_BUFFER_NV
cores/libretro-ffmpeg/ffmpeg_core.c:1530:24: error: implicit declaration of function ‘glMapBufferRange’; did you mean ‘glMapBufferRangeEXT’? [-Wimplicit-function-declaration]
 1530 |    buffer = (GLshort*)(glMapBufferRange(GL_PIXEL_UNPACK_BUFFER, 0,
      |                        ^~~~~~~~~~~~~~~~
      |                        glMapBufferRangeEXT
cores/libretro-ffmpeg/ffmpeg_core.c:1537:7: error: implicit declaration of function ‘glUnmapBuffer’; did you mean ‘glUnmapBufferOES’? [-Wimplicit-function-declaration]
 1537 |       glUnmapBuffer(GL_PIXEL_UNPACK_BUFFER);
      |       ^~~~~~~~~~~~~
      |       glUnmapBufferOES
cores/libretro-ffmpeg/ffmpeg_core.c:1540:10: error: ‘GL_RG_INTEGER’ undeclared (first use in this function); did you mean ‘GL_RED_INTEGER’?
 1540 |          GL_RG_INTEGER, GL_SHORT, NULL);
      |          ^~~~~~~~~~~~~
      |          GL_RED_INTEGER
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘hwfft_render’:
cores/libretro-ffmpeg/ffmpeg_core.c:1680:67: error: ‘GL_DEPTH_STENCIL_ATTACHMENT’ undeclared (first use in this function); did you mean ‘GL_STENCIL_ATTACHMENT’?
 1680 |       static const GLenum attachments[] = { GL_COLOR_ATTACHMENT0, GL_DEPTH_STENCIL_ATTACHMENT };
      |                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                   GL_STENCIL_ATTACHMENT
cores/libretro-ffmpeg/ffmpeg_core.c:1682:25: error: ‘GL_READ_FRAMEBUFFER’ undeclared (first use in this function); did you mean ‘GL_READ_FRAMEBUFFER_NV’?
 1682 |       glBindFramebuffer(GL_READ_FRAMEBUFFER, fft->ms_fbo);
      |                         ^~~~~~~~~~~~~~~~~~~
      |                         GL_READ_FRAMEBUFFER_NV
cores/libretro-ffmpeg/ffmpeg_core.c:1683:25: error: ‘GL_DRAW_FRAMEBUFFER’ undeclared (first use in this function); did you mean ‘GL_DRAW_FRAMEBUFFER_NV’?
 1683 |       glBindFramebuffer(GL_DRAW_FRAMEBUFFER, backbuffer);
      |                         ^~~~~~~~~~~~~~~~~~~
      |                         GL_DRAW_FRAMEBUFFER_NV
cores/libretro-ffmpeg/ffmpeg_core.c:1684:7: error: implicit declaration of function ‘glBlitFramebuffer’; did you mean ‘glBindFramebuffer’? [-Wimplicit-function-declaration]
 1684 |       glBlitFramebuffer(0, 0, width, height, 0, 0, width, height,
      |       ^~~~~~~~~~~~~~~~~
      |       glBindFramebuffer
cores/libretro-ffmpeg/ffmpeg_core.c:1688:7: error: implicit declaration of function ‘glInvalidateFramebuffer’; did you mean ‘glDeleteFramebuffers’? [-Wimplicit-function-declaration]
 1688 |       glInvalidateFramebuffer(GL_FRAMEBUFFER, 2, attachments);
      |       ^~~~~~~~~~~~~~~~~~~~~~~
```

### Expected behavior

Expecting the build to finish without errors.

### Steps to reproduce the bug

1. Configure the build with 
   ``` sh
    ./configure --enable-opengles --disable-opengl_core --disable-vulkan --disable-opengl1 --disable-qt
    ```

2. Run `make` and notice the build errors.

### Version/Commit

Git 36b25315fd2a705e5eb9b1cbdd55ddd98bcd656d

### Present in the nightly version

Yes, this is reproduced in the nightly build

### Platform & operating system

Linux aarch64, RaspiOS (trixie)

### Affected Cores

FFMPEG (internal)

### Relevant log output

```shell

```

**Comment by hizzlekizzle** [comment]
Hmm, this appears to be related to the FFT, which explicitly requires GLES3. This was previously in a separate file, and I guess maybe was optional to include...?

@LibretroAdmin this appears to have started with https://github.com/libretro/RetroArch/commit/1e297d490972fe334b9306899a0c48e7bcd1d7f8

**Comment by LibretroAdmin** [comment]
Stopgap fix for now
https://github.com/libretro/RetroArch/commit/acd48dfe31c9551d28a32639d722dd42897550f9

The FFT visualizer is a nice idea that might be more at home in RetroArch especially now with its rapidly expanding media compatibility. Just need to get it working across all graphics APIs.

**Comment by cmitu** [comment]
Thank you for taking a look. After https://github.com/libretro/RetroArch/commit/acd48dfe31c9551d28a32639d722dd42897550f9, the build works fine so I'd say this is solved.

I noticed you re-opened the issue - do you want to keep it open until a more permanent solution is added ?

**Comment by LibretroAdmin** [comment]
Nah it can be closed. Thanks for testing.
