### ISSUE TITLE
Fail to build with ffmpeg 7.0

### ISSUE THREAD

**Issue by marillat** [libretro/RetroArch#16437]
Debian unstable amd64 ffmpeg 7.0
Deprecated functions before ffmpeg 6.1 have been removed in ffmpeg 7.0
```
CC record/drivers/record_ffmpeg.c
record/drivers/record_ffmpeg.c: In function 'ffmpeg_init_audio':
record/drivers/record_ffmpeg.c:304:16: error: 'AVCodecContext' has no member named 'channels'
  304 |    audio->codec->channels       = param->channels;
      |                ^~
record/drivers/record_ffmpeg.c:305:18: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
  305 |    audio->codec->channel_layout = (param->channels > 1)
      |                  ^~~~~~~~~~~~~~
      |                  ch_layout
record/drivers/record_ffmpeg.c:356:22: error: 'AVCodecContext' has no member named 'channels'
  356 |          audio->codec->channels *
      |                      ^~
record/drivers/record_ffmpeg.c: In function 'encode_audio':
record/drivers/record_ffmpeg.c:1345:11: error: 'AVFrame' has no member named 'channel_layout'; did you mean 'ch_layout'?
 1345 |    frame->channel_layout = handle->audio.codec->channel_layout;
      |           ^~~~~~~~~~~~~~
      |           ch_layout
record/drivers/record_ffmpeg.c:1345:49: error: 'AVCodecContext' has no member named 'channel_layout'; did you mean 'ch_layout'?
 1345 |    frame->channel_layout = handle->audio.codec->channel_layout;
      |                                                 ^~~~~~~~~~~~~~
      |                                                 ch_layout
record/drivers/record_ffmpeg.c:1352:29: error: 'AVCodecContext' has no member named 'channels'
 1352 |          handle->audio.codec->channels,
      |                             ^~
record/drivers/record_ffmpeg.c:1358:29: error: 'AVCodecContext' has no member named 'channels'
 1358 |          handle->audio.codec->channels,
      |                             ^~
make: *** [Makefile:209: obj-unix/release/record/drivers/record_ffmpeg.o] Error 1
```

**Comment by phial3** [comment]
+1

**Comment by hizzlekizzle** [comment]
Yeah, every couple of years we have to decide to either update or vendor. Guess it's that time again -_-

**Comment by eclipseo** [comment]
I'm working on multiple patches to include FFMPEG 7 in Fedora Rawhide, including Retroarch.

The patch above has been tested with FFMPEG 6.1.1 https://koji.fedoraproject.org/koji/taskinfo?taskID=117292404 and FFMPEG 7.0 : https://copr.fedorainfracloud.org/coprs/eclipseo/svt-av1-2.0.0/build/7412641/

Though there is no reason it wouldn't work with previous FFMPEG as we check the libavutil version to enable the new features.
