### PR TITLE
Disabled menu buildfixes

### LINKED ISSUE #16880: Current RetroArch cannot build with the menu disabled
## Description

While troubleshooting a Haiku issue, I noticed that running `./configure --disable-menu` unfortunately does not allow RetroArch to build. This is not Haiku-specific and also happens on Linux (and I am assuming on most, if not all, archs)

### Expected behavior

RetroArch should build, albeit with the menu disabled.

### Actual behavior

```
CC retroarch.c
retroarch.c: In function ‘command_event’:
retroarch.c:4469:46: warning: implicit declaration of function ‘menu_state_get_ptr’; did you mean ‘uico_state_get_ptr’? [-Wimplicit-function-declaration]
 4469 |             struct menu_state *menu_st     = menu_state_get_ptr();
      |                                              ^~~~~~~~~~~~~~~~~~
      |                                              uico_state_get_ptr
retroarch.c:4469:46: warning: initialization of ‘struct menu_state *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
retroarch.c:4528:26: error: invalid use of undefined type ‘struct menu_state’
 4528 |                   menu_st->flags                  |= MENU_ST_FLAG_ENTRIES_NEED_REFRESH;
      |                          ^~
retroarch.c:4528:54: error: ‘MENU_ST_FLAG_ENTRIES_NEED_REFRESH’ undeclared (first use in this function)
 4528 |                   menu_st->flags                  |= MENU_ST_FLAG_ENTRIES_NEED_REFRESH;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
retroarch.c:4528:54: note: each undeclared identifier is reported only once for each function it appears in
retroarch.c:4529:30: error: invalid use of undefined type ‘struct menu_state’
 4529 |                   if (menu_st->driver_ctx->environ_cb)
      |                              ^~
retroarch.c:4530:29: error: invalid use of undefined type ‘struct menu_state’
 4530 |                      menu_st->driver_ctx->environ_cb(MENU_ENVIRON_RESET_HORIZONTAL_LIST,
      |                             ^~
retroarch.c:4530:54: error: ‘MENU_ENVIRON_RESET_HORIZONTAL_LIST’ undeclared (first use in this function)
 4530 |                      menu_st->driver_ctx->environ_cb(MENU_ENVIRON_RESET_HORIZONTAL_LIST,
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
retroarch.c:4531:41: error: invalid use of undefined type ‘struct menu_state’
 4531 |                            NULL, menu_st->userdata);
      |                                         ^~
make: *** [Makefile:209: obj-unix/release/retroarch.o] Error 1
```

### Steps to reproduce the bug

1. git clone the latest version of RA
2. `./configure --disable-menu`
3. `make`

### Bisect Results

According to @sonninnos this was possibly introduced in 87b9d0328e0 but there are various errors at various stages.
I have a pull request ready that will allow building with `--disable-menu --disable-cheevos --disable-qt --disable-slang` but not `--disable-menu` alone.

### Version/Commit

- RetroArch: a759e601484c2202a6a3460b4dd5de708bb41821

### Environment information

- OS: Debian GNU/Linux / Haiku
- Compiler: gcc 12.2.0 / gcc 13.3.0

### PR DESCRIPTION
**Pull request by sonninnos**

### CODE REVIEW

**Comment by viachaslavic** [comment]
This partially close https://github.com/libretro/RetroArch/issues/16880#issuecomment-2473723748, not the entire issue.

**Comment by sonninnos** [comment]
What errors are remaining that prevent the building? Warnings don't count.

**Comment by viachaslavic** [comment]
1. Issue with gcc 14 https://github.com/libretro/RetroArch/pull/16881#issuecomment-2291623506 , which cannot find the declaration.
2. Qt handling in build scripts https://github.com/libretro/RetroArch/issues/16880#issuecomment-2305581184

Both cases are not related to #16929 , so It's too early to close linked issue until they are resolved.

**Comment by sonninnos** [comment]
Sure, any kind of thumbnail download task thing makes absolutely zero sense with menu disabled, so the whole file should not be included at all.

**Comment by viachaslavic** [comment]
`task_pl_thumbnail_download.c` can be fixed with a simple including header

```patch
diff --git a/tasks/task_pl_thumbnail_download.c b/tasks/task_pl_thumbnail_download.c
index 71b397e87a..359c909200 100644
--- a/tasks/task_pl_thumbnail_download.c
+++ b/tasks/task_pl_thumbnail_download.c
@@ -32,6 +32,7 @@
 #include "../configuration.h"
 #include "../file_path_special.h"
 #include "../playlist.h"
+#include "../runloop.h"
 #include "../verbosity.h"

 #ifdef RARCH_INTERNAL
 ```patch

**Comment by sonninnos** [comment]
Nice, but let's do this instead

```diff
diff --git a/Makefile.common b/Makefile.common
index c73350c8b6..f3ca6f44bc 100644
--- a/Makefile.common
+++ b/Makefile.common
@@ -336,13 +336,17 @@ OBJ += \
        gfx/video_driver.o \
        gfx/gfx_display.o \
        gfx/gfx_animation.o \
-       gfx/gfx_thumbnail_path.o \
-       gfx/gfx_thumbnail.o \
        configuration.o \
        $(LIBRETRO_COMM_DIR)/dynamic/dylib.o \
        cores/dynamic_dummy.o \
        $(LIBRETRO_COMM_DIR)/queues/message_queue.o

+ifeq ($(HAVE_MENU), 1)
+   OBJ += \
+       gfx/gfx_thumbnail_path.o \
+       gfx/gfx_thumbnail.o
+endif
+
 ifeq ($(HAVE_MICROPHONE), 1)
    DEFINES += -DHAVE_MICROPHONE
    OBJ += audio/microphone_driver.o
@@ -2166,9 +2170,12 @@ ifeq ($(HAVE_NETWORKING), 1)
           tasks/task_http.o \
           tasks/task_netplay_lan_scan.o \
           tasks/task_netplay_nat_traversal.o \
-         tasks/task_pl_thumbnail_download.o \
           tasks/task_netplay_find_content.o

+   ifeq ($(HAVE_MENU), 1)
+      OBJ += tasks/task_pl_thumbnail_download.o
+   endif
+
    ifeq ($(HAVE_MENU_COMMON), 1)
       OBJ += tasks/task_core_updater.o
    endif
```

**Comment by viachaslavic** [comment]
Great! Now it compiles correctly and works on Arch, but only with an explicit `--disable-qt`.
We can leave the issue of transitive inclusions for a separate discussion in the future.
