### PR TITLE
Fix the C89 build with mingw 4.0.4.

### PR DESCRIPTION
**Pull request by orbea**
## Description

This is kind of ugly, but I think there is not another way with C89 even if most compilers do not complain.

> In C89 initializer lists must be constant expressions known at compile-time.

Source: https://stackoverflow.com/questions/42306921/initializer-element-not-computable-at-load-time/42310398#42310398

Also in C89 the assignments have to be done line by line.

Source: https://stackoverflow.com/questions/13275751/expected-expression-before-token/13275995#13275995

## Related Issues

mingw-w64-4.0.4 in travis xenial fails with `C89_BUILD=1`.
```
menu/menu_displaylist.c: In function ‘menu_displaylist_parse_system_info’:
menu/menu_displaylist.c:730:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_libretrodb_supp, MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBRETRODB_SUPPORT},
           ^
menu/menu_displaylist.c:730:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_libretrodb_supp, MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBRETRODB_SUPPORT},
          ^
menu/menu_displaylist.c:731:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_overlay_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OVERLAY_SUPPORT},
           ^
menu/menu_displaylist.c:731:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_overlay_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OVERLAY_SUPPORT},
          ^
menu/menu_displaylist.c:732:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_command_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COMMAND_IFACE_SUPPORT},
           ^
menu/menu_displaylist.c:732:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_command_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COMMAND_IFACE_SUPPORT},
          ^
menu/menu_displaylist.c:733:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_network_command_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_COMMAND_IFACE_SUPPORT},
           ^
menu/menu_displaylist.c:733:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_network_command_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_COMMAND_IFACE_SUPPORT},
          ^
menu/menu_displaylist.c:734:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_network_gamepad_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_REMOTE_SUPPORT},
           ^
menu/menu_displaylist.c:734:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_network_gamepad_supp,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETWORK_REMOTE_SUPPORT},
          ^
menu/menu_displaylist.c:735:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_cocoa_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COCOA_SUPPORT},
           ^
menu/menu_displaylist.c:735:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_cocoa_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COCOA_SUPPORT},
          ^
menu/menu_displaylist.c:736:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rpng_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RPNG_SUPPORT},
           ^
menu/menu_displaylist.c:736:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rpng_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RPNG_SUPPORT},
          ^
menu/menu_displaylist.c:737:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rjpeg_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RJPEG_SUPPORT},
           ^
menu/menu_displaylist.c:737:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rjpeg_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RJPEG_SUPPORT},
          ^
menu/menu_displaylist.c:738:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rbmp_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RBMP_SUPPORT},
           ^
menu/menu_displaylist.c:738:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rbmp_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RBMP_SUPPORT},
          ^
menu/menu_displaylist.c:739:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rtga_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RTGA_SUPPORT},
           ^
menu/menu_displaylist.c:739:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rtga_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RTGA_SUPPORT},
          ^
menu/menu_displaylist.c:740:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_SUPPORT},
           ^
menu/menu_displaylist.c:740:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_SUPPORT},
          ^
menu/menu_displaylist.c:741:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl2_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL2_SUPPORT},
           ^
menu/menu_displaylist.c:741:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl2_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL2_SUPPORT},
          ^
menu/menu_displaylist.c:742:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_vulkan_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VULKAN_SUPPORT},
           ^
menu/menu_displaylist.c:742:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_vulkan_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_VULKAN_SUPPORT},
          ^
menu/menu_displaylist.c:743:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_metal_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_METAL_SUPPORT},
           ^
menu/menu_displaylist.c:743:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_metal_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_METAL_SUPPORT},
          ^
menu/menu_displaylist.c:744:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_opengl_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGL_SUPPORT},
           ^
menu/menu_displaylist.c:744:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_opengl_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGL_SUPPORT},
          ^
menu/menu_displaylist.c:745:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_opengles_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGLES_SUPPORT},
           ^
menu/menu_displaylist.c:745:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_opengles_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENGLES_SUPPORT},
          ^
menu/menu_displaylist.c:746:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_thread_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_THREADING_SUPPORT},
           ^
menu/menu_displaylist.c:746:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_thread_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_THREADING_SUPPORT},
          ^
menu/menu_displaylist.c:747:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_kms_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_KMS_SUPPORT},
           ^
menu/menu_displaylist.c:747:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_kms_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_KMS_SUPPORT},
          ^
menu/menu_displaylist.c:748:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_udev_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_UDEV_SUPPORT},
           ^
menu/menu_displaylist.c:748:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_udev_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_UDEV_SUPPORT},
          ^
menu/menu_displaylist.c:749:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_vg_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENVG_SUPPORT},
           ^
menu/menu_displaylist.c:749:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_vg_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENVG_SUPPORT},
          ^
menu/menu_displaylist.c:750:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_egl_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_EGL_SUPPORT},
           ^
menu/menu_displaylist.c:750:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_egl_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_EGL_SUPPORT},
          ^
menu/menu_displaylist.c:751:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_x11_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_X11_SUPPORT},
           ^
menu/menu_displaylist.c:751:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_x11_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_X11_SUPPORT},
          ^
menu/menu_displaylist.c:752:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_wayland_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WAYLAND_SUPPORT},
           ^
menu/menu_displaylist.c:752:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_wayland_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WAYLAND_SUPPORT},
          ^
menu/menu_displaylist.c:753:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_xvideo_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XVIDEO_SUPPORT},
           ^
menu/menu_displaylist.c:753:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_xvideo_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XVIDEO_SUPPORT},
          ^
menu/menu_displaylist.c:754:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_alsa_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ALSA_SUPPORT},
           ^
menu/menu_displaylist.c:754:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_alsa_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ALSA_SUPPORT},
          ^
menu/menu_displaylist.c:755:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_oss_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OSS_SUPPORT},
           ^
menu/menu_displaylist.c:755:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_oss_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OSS_SUPPORT},
          ^
menu/menu_displaylist.c:756:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_al_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENAL_SUPPORT},
           ^
menu/menu_displaylist.c:756:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_al_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENAL_SUPPORT},
          ^
menu/menu_displaylist.c:757:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sl_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENSL_SUPPORT},
           ^
menu/menu_displaylist.c:757:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sl_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_OPENSL_SUPPORT},
          ^
menu/menu_displaylist.c:758:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rsound_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RSOUND_SUPPORT},
           ^
menu/menu_displaylist.c:758:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_rsound_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_RSOUND_SUPPORT},
          ^
menu/menu_displaylist.c:759:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_roar_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ROARAUDIO_SUPPORT},
           ^
menu/menu_displaylist.c:759:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_roar_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ROARAUDIO_SUPPORT},
          ^
menu/menu_displaylist.c:760:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_jack_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_JACK_SUPPORT},
           ^
menu/menu_displaylist.c:760:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_jack_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_JACK_SUPPORT},
          ^
menu/menu_displaylist.c:761:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_pulse_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PULSEAUDIO_SUPPORT},
           ^
menu/menu_displaylist.c:761:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_pulse_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PULSEAUDIO_SUPPORT},
          ^
menu/menu_displaylist.c:762:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coreaudio_supp      ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COREAUDIO_SUPPORT},
           ^
menu/menu_displaylist.c:762:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coreaudio_supp      ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COREAUDIO_SUPPORT},
          ^
menu/menu_displaylist.c:763:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coreaudio3_supp     ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COREAUDIO3_SUPPORT},
           ^
menu/menu_displaylist.c:763:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coreaudio3_supp     ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_COREAUDIO3_SUPPORT},
          ^
menu/menu_displaylist.c:764:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dsound_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DSOUND_SUPPORT},
           ^
menu/menu_displaylist.c:764:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dsound_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DSOUND_SUPPORT},
          ^
menu/menu_displaylist.c:765:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_wasapi_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WASAPI_SUPPORT},
           ^
menu/menu_displaylist.c:765:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_wasapi_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_WASAPI_SUPPORT},
          ^
menu/menu_displaylist.c:766:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_xaudio_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XAUDIO2_SUPPORT},
           ^
menu/menu_displaylist.c:766:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_xaudio_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_XAUDIO2_SUPPORT},
          ^
menu/menu_displaylist.c:767:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_zlib_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ZLIB_SUPPORT},
           ^
menu/menu_displaylist.c:767:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_zlib_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_ZLIB_SUPPORT},
          ^
menu/menu_displaylist.c:768:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_7zip_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_7ZIP_SUPPORT},
           ^
menu/menu_displaylist.c:768:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_7zip_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_7ZIP_SUPPORT},
          ^
menu/menu_displaylist.c:769:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dylib_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYLIB_SUPPORT},
           ^
menu/menu_displaylist.c:769:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dylib_supp          ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYLIB_SUPPORT},
          ^
menu/menu_displaylist.c:770:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dynamic_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYNAMIC_SUPPORT},
           ^
menu/menu_displaylist.c:770:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_dynamic_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_DYNAMIC_SUPPORT},
          ^
menu/menu_displaylist.c:771:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_cg_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CG_SUPPORT},
           ^
menu/menu_displaylist.c:771:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_cg_supp             ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CG_SUPPORT},
          ^
menu/menu_displaylist.c:772:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_glsl_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GLSL_SUPPORT},
           ^
menu/menu_displaylist.c:772:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_glsl_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_GLSL_SUPPORT},
          ^
menu/menu_displaylist.c:773:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_hlsl_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_HLSL_SUPPORT},
           ^
menu/menu_displaylist.c:773:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_hlsl_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_HLSL_SUPPORT},
          ^
menu/menu_displaylist.c:774:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl_image_supp      ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_IMAGE_SUPPORT},
           ^
menu/menu_displaylist.c:774:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_sdl_image_supp      ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_SDL_IMAGE_SUPPORT},
          ^
menu/menu_displaylist.c:775:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_ffmpeg_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FFMPEG_SUPPORT},
           ^
menu/menu_displaylist.c:775:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_ffmpeg_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FFMPEG_SUPPORT},
          ^
menu/menu_displaylist.c:776:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_mpv_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_MPV_SUPPORT},
           ^
menu/menu_displaylist.c:776:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_mpv_supp            ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_MPV_SUPPORT},
          ^
menu/menu_displaylist.c:777:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coretext_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CORETEXT_SUPPORT},
           ^
menu/menu_displaylist.c:777:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_coretext_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_CORETEXT_SUPPORT},
          ^
menu/menu_displaylist.c:778:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_freetype_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FREETYPE_SUPPORT},
           ^
menu/menu_displaylist.c:778:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_freetype_supp       ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_FREETYPE_SUPPORT},
          ^
menu/menu_displaylist.c:779:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_stbfont_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_STB_TRUETYPE_SUPPORT},
           ^
menu/menu_displaylist.c:779:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_stbfont_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_STB_TRUETYPE_SUPPORT},
          ^
menu/menu_displaylist.c:780:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_netplay_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETPLAY_SUPPORT},
           ^
menu/menu_displaylist.c:780:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_netplay_supp        ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_NETPLAY_SUPPORT},
          ^
menu/menu_displaylist.c:781:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_python_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PYTHON_SUPPORT},
           ^
menu/menu_displaylist.c:781:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_python_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_PYTHON_SUPPORT},
          ^
menu/menu_displaylist.c:782:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_v4l2_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_V4L2_SUPPORT},
           ^
menu/menu_displaylist.c:782:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_v4l2_supp           ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_V4L2_SUPPORT},
          ^
menu/menu_displaylist.c:783:11: error: initializer element is not computable at load time [-Werror=pedantic]
          {_libusb_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBUSB_SUPPORT},
           ^
menu/menu_displaylist.c:783:10: error: initializer element is not computable at load time [-Werror=pedantic]
          {_libusb_supp         ,    MENU_ENUM_LABEL_VALUE_SYSTEM_INFO_LIBUSB_SUPPORT},
          ^
```

## Related Pull Requests

This was exposed and is blocking PR https://github.com/libretro/RetroArch/pull/8621.

### CODE REVIEW

**Comment by twinaphex** [comment]
This PR will likely have to wait and likely won't be merged in this fashion. I have a different way to solve this issue, but it will take some more time.

**Comment by orbea** [comment]
@twinaphex It should be sooner rather than later, our travis is install is EOL and ubuntu has already been deleting documentation.

**Comment by orbea** [comment]
@twinaphex Would you mind doing what you had in mind so travis can be fully fixed? Or should this PR be rebased in the meantime?
