### ISSUE TITLE
[PC] Debug Build Broken

### ISSUE THREAD

**Issue by kikmon** [libretro/RetroArch#14253]
## Description

Windows Debug build seems to be broken since https://github.com/libretro/RetroArch/commit/592f9384b077e605769fab813bcaa5a916bf3774#diff-37c1e375088077a96f420796d9964c1c8082367e384c998abc244b60c17284d8
and the change in task_database.c

Maybe we can add debug build to Gihub Action's Retroarch CI ?

### Expected behavior

Being able to build in Debug

### Actual behavior

Build error 
RetroArch\tasks\task_database.c(269,25): error C2065: 'rv': undeclared identifier

### Steps to reproduce the bug

Build in Debug Mode

### Bisect Results

seems to have started here
https://github.com/libretro/RetroArch/commit/592f9384b077e605769fab813bcaa5a916bf3774#diff-37c1e375088077a96f420796d9964c1c8082367e384c998abc244b60c17284d8

### Environment information

- OS: Windows 11
- Compiler: Visual 2022

**Comment by LibretroAdmin** [comment]
Should be fixed -
https://github.com/libretro/RetroArch/commit/19e4b8c0ca76e516b5c90040edad549d3cd75d6e
