### ISSUE TITLE
Haiku build broken

### ISSUE THREAD

**Issue by kwyxz** [libretro/RetroArch#7549]
Looks like Haiku build is now broken, possibly since commit 521b978d3105e9c8a70517a4e076282e009977ed

Here's the output when attempting to build:

```
LD retroarch
/boot/system/develop/tools/bin/../lib/gcc/x86_64-unknown-haiku/7.3.0/../../../../x86_64-unknown-haiku/bin/ld: obj-unix/release/./libretro-common/rthreads/rthreads.o: in function `sthread_create_with_priority':
rthreads.c:(.text+0xf7): undefined reference to `pthread_attr_setschedpolicy'
collect2: error: ld returned 1 exit status
Makefile:187: recipe for target 'retroarch' failed
make: *** [retroarch] Error 1
```

I'll do my best to investigate this when I can, unless someone has an idea of what is happening and can help.

**Comment by bparker06** [comment]
Apparently [Haiku doesn't support pthread_attr_setschedpolicy](http://minisoc.xyz/HaikuMono/).

**Comment by kwyxz** [comment]
Thank you for looking into this @bparker06 

This article seems helpful. I wish it had a timestamp though in order to know how long ago it was written... during my initial research, I did find this in Haiku's header files:
```
/system/develop> grep -R pthread_attr_setschedpolicy *
headers/posix/pthread.h:extern int pthread_attr_setschedpolicy(pthread_attr_t *attr, int policy);
```
which led me to believe that the function was there, but maybe not fully implemented. I'll try to spend time on this soon.

**Comment by kwyxz** [comment]
Quick update: [it might be ifdef'ed out in the header file](https://www.freelists.org/post/haiku-bugs/Haiku-13307-pthread-attr-setschedpolicy-needs-implementation)

**Comment by kwyxz** [comment]
Adding [this bug report](https://issues.apache.org/jira/browse/THRIFT-3498) here too for later reference

**Comment by kwyxz** [comment]
Pushed a temp fix in #7585
