### ISSUE TITLE
ffmpeg build issue on Linux

### ISSUE THREAD

**Issue by Sanaki** [libretro/RetroArch#9886]
## Description

Build fails due to the ffmpeg core starting today

### Expected behavior

Build succeeds

### Actual behavior

```
cores/libretro-ffmpeg/video_buffer.c: In function ‘video_buffer_create’:
cores/libretro-ffmpeg/video_buffer.c:73:25: error: ‘video_decoder_context_t {aka struct video_decoder_context}’ has no member named ‘hw_source’; did you mean ‘source’?
           !b->buffer[i].hw_source ||
                         ^~~~~~~~~
                         source
Makefile:211: recipe for target 'obj-unix/release/cores/libretro-ffmpeg/video_buffer.o' failed
```

### Steps to reproduce the bug

1. Pull Retroarch source
2. ./configure && make clean && make -j5

### Bisect Results

c6309d963d80d2ada03dfd863bcae602095d5869 is the first bad commit

### Environment information

- OS: Linux Mint 19.3
- Compiler: GCC 7.4.0 64-bit

**Comment by twinaphex** [comment]
Pinging @hasenbanck for this one.

@Sanaki I think the problem here could be the libavutil version you have on your OS -

#if LIBAVUTIL_VERSION_MAJOR > 55

https://github.com/libretro/RetroArch/blob/master/cores/libretro-ffmpeg/video_buffer.h#L37

So if libavutil is below version 55, it appears this part is not exposed.

**Comment by twinaphex** [comment]
Try to see if this commit helps you -

https://github.com/libretro/RetroArch/commit/31a7f2b

**Comment by Sanaki** [comment]
That did it. Thank you.

**Comment by hasenbanck** [comment]
Awww, I forgot to guard that hw_frame with a ifdef. Mea culpa.

@twinaphex thank you for fixing this.

I will try to write a local testscript to test against this kind of error.
