### PR TITLE
fix building against ffmpeg 5.0

### LINKED ISSUE #13530: Can't compile with FFMPEG5 - Retroarch 1.10.0
## Description

We have already migrated to FFMPEG 5 and when trying to compile Retroarch (1.10.0 in this case) I get a compilation error:

```
error: 'AVPicture' undeclared (first use in this function); did you mean 'AVPictureType'?
DEBUG util.py:634:     77 |       avpicture_alloc((AVPicture*)b->buffer[i].target,
DEBUG util.py:634:        |                        ^~~~~~~~~
DEBUG util.py:634:        |                        AVPictureType
DEBUG util.py:634:  cores/libretro-ffmpeg/video_buffer.c:77:24: note: each undeclared identifier is reported only once for each function it appears in
DEBUG util.py:634:  cores/libretro-ffmpeg/video_buffer.c:77:34: error: expected expression before ')' token
DEBUG util.py:634:     77 |       avpicture_alloc((AVPicture*)b->buffer[i].target,
```
Full build log here: https://file-store.openmandriva.org/api/v1/file_stores/a643d96e109621fa2140ee6e3c70eaa43f4611c7.log?show=true

Which indicates incompatibility with the newly released Ffmpeg5.
It is worth adding that if I use compact ffmpeg4 version, everything compiles correctly.

### Expected behavior

All compiles fine with ffmpeg5

### Steps to reproduce the bug

1. Upgrade ffmpeg to version 5
2. Try compile retroarch 1.10.0
3. See build error

### Environment information

- OS: OpenMandriva Cooker
- Compiler: LLVM/Clang 13.0.0

### PR DESCRIPTION
**Pull request by keithbowes**
## Description

This is a continuation of @alucryd's excellent work in PR #13542.  I've fixed the segfault and various other issues.  It works perfectly with FFmpeg 4, but there's no audio with FFmpeg 5; I have no idea why, as it seems that everything is working properly, but for some reason, none of the audio data is actually being written to the file (the video works fine and the FFmpeg API calls used for both the audio and the video seem to be mostly the same, so I don't know why one works and one doesn't; I must have overlooked something somewhere).

## Related Issues

As with alucryd's original PR, this fixes #13530.

### CODE REVIEW

**Comment by hizzlekizzle** [comment]
eyyy, that's awesome!

For the audio, IIRC, a verbose log will explain that it's using a deprecated API call that was apparently completely removed sometime before 5.0 dropped.

**Comment by keithbowes** [comment]
OK, I got the audio working (it turns out I had to call `av_frame_get_buffer()`), squashed the commits (as per the guidelines), and did a force-push.

**Comment by hizzlekizzle** [comment]
This is great. let's get some eyes on it for review: @twinaphex @jdgleaver 

I'm not sure why the LGTM analysis is saying it failed to build the base commit, since following the details link takes it to a bunch of green "success" checkmarks.

**Comment by alucryd** [comment]
Good job! I'll backport it in the Arch Linux package when I have the chance, thanks!

**Comment by jdgleaver** [comment]
Well, this is great, but it means we lose ffmpeg support on all older Linux distributions (and some new ones, including the one I use) which still ship ffmpeg v3 by default. It also means we lose ffmpeg support for the Linux binaries we produce via our build system (where the build container we use only has ffmpeg v3 available)

Since this is likely to become an increasingly large issue as distros continue to update or lag behind on ffmpeg versions, it would seem that we need to think about bundling an ffmpeg source tree with RetroArch itself (similar to what PPSSPP standalone does - which still uses v3 FWIW)

**Comment by keithbowes** [comment]
> This is great. let's get some eyes on it for review: @twinaphex @jdgleaver
> 
> I'm not sure why the LGTM analysis is saying it failed to build the base commit, since following the details link takes it to a bunch of green "success" checkmarks.

That's a problem shared by several consecutive PRs, so I won't take it seriously, for now.



> Well, this is great, but it means we lose ffmpeg support on all older Linux distributions (and some new ones, including the one I use) which still ship ffmpeg v3 by default. It also means we lose ffmpeg support for the Linux binaries we produce via our build system (where the build container we use only has ffmpeg v3 available)

I was unaware that some distros ship with v3 (for the distro I use, you have to go back a few EOL versions to get ffmpeg v3).  I was glad that I could clean up all the #ifdefs but I could reintroduce enough to get it to compile if with v3.  BTW, the AppImage doesn't include ffmpeg support at all; I downloaded the 1.10.0 AppImage to see if libdecor was included, and neither it nor ffmpeg was compiled in.

**Comment by jdgleaver** [comment]
> BTW, the AppImage doesn't include ffmpeg support at all; I downloaded the 1.10.0 AppImage to see if libdecor was included, and neither it nor ffmpeg was compiled in.

Yes, apologies - you are entirely correct (not sure how I forgot about that...)

>  I was glad that I could clean up all the #ifdefs but I could reintroduce enough to get it to compile if with v3. 

Given that we don't include ffmpeg support in the AppImage builds, I guess backwards compatibility is less of an issue than I thought. And indeed - a rats' nest of #ifdefs does not make for clean and maintainable code...

On reflection, then, I don't see any overriding reason not to drop v3 support.

Bundling ffmpeg with RetroArch would still be the ultimate solution, though (albeit with an annoying increase in repo size and compilation time...)
